### ISSUE TITLE
seemh下载不了。

### ISSUE THREAD

**Issue by starobots** [eight04/ComicCrawler#100]
seemh和mhgui的链接会出错误。
dm5和178就没事。
麻烦大佬！

这个是返回的故障信息：

Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\lib\site-packages\comiccrawler\core\__init__.py", line 581, in error_loop
    process()
  File "c:\program files (x86)\python36-32\lib\site-packages\comiccrawler\core\__init__.py", line 531, in download
    crawler.init()
  File "c:\program files (x86)\python36-32\lib\site-packages\comiccrawler\core\__init__.py", line 372, in init
    self.init_images(self.ep.current_page - 1)
  File "c:\program files (x86)\python36-32\lib\site-packages\comiccrawler\core\__init__.py", line 379, in init_images
    self.get_images()
  File "c:\program files (x86)\python36-32\lib\site-packages\comiccrawler\core\__init__.py", line 498, in get_images
    self.ep.current_url
  File "c:\program files (x86)\python36-32\lib\site-packages\comiccrawler\mods\seemh.py", line 121, in get_images
    images = vm.call("getFiles", path, files, host)
  File "c:\program files (x86)\python36-32\lib\site-packages\node_vm2\__init__.py", line 150, in call
    "args": args
  File "c:\program files (x86)\python36-32\lib\site-packages\node_vm2\__init__.py", line 99, in communicate
    raise VMError(data["error"])
node_vm2.VMError: location is not defined

**Comment by eight04** [comment]
URL reported in #101: http://tw.manhuagui.com/comic/26767/

**Comment by starobots** [comment]
修复了，谢谢eight。

**Comment by eight04** [comment]
你是直接從 Github 拉取的嗎？還沒 release 前先不要 close issue。

**Comment by eight04** [comment]
於 2018.3.7 修正。
