### ISSUE TITLE
看漫畫下載出現錯誤

### ISSUE THREAD

**Issue by kesdoputr** [eight04/ComicCrawler#101]
抓下面這本的時候一直下不來

http://tw.manhuagui.com/comic/26767/

Start download DARLING in the FRANXX
Start downloading DARLING in the FRANXX
total 15 episode.
Downloading ep 第09回
Traceback (most recent call last):
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 581, in
 error_loop
    process()
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 531, in
 download
    crawler.init()
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 372, in
 init
    self.init_images(self.ep.current_page - 1)
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 379, in
 init_images
    self.get_images()
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 498, in
 get_images
    self.ep.current_url
  File "c:\python\lib\site-packages\comiccrawler\mods\seemh.py", line 121, in ge
t_images
    images = vm.call("getFiles", path, files, host)
  File "c:\python\lib\site-packages\node_vm2\__init__.py", line 150, in call
    "args": args
  File "c:\python\lib\site-packages\node_vm2\__init__.py", line 99, in communica
te
    raise VMError(data["error"])
node_vm2.VMError: location is not defined

**Comment by eight04** [comment]
Duplicated with #100
