### ISSUE TITLE
seemh疑似再次改版

### ISSUE THREAD

**Issue by IthildinX** [eight04/ComicCrawler#103]
看漫畫今天好像又改版了 已更新 v2018.3.7 下載時出現錯誤 
發生的行數跟 #100不同 應該是新的狀況

連結 
http://tw.manhuagui.com/comic/18158/
http://www.manhuagui.com/comic/15284/

CMD錯誤內容
Traceback (most recent call last):
File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\core_init_.py", line 582, in error_loop
process()
File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\core_init_.py", line 532, in download
crawler.init()
File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\core_init_.py", line 373, in init
self.init_images(self.ep.current_page - 1)
File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\core_init_.py", line 380, in init_images
self.get_images()
File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\core_init_.py", line 499, in get_images
self.ep.current_url
File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\mods\seemh.py", line 74, in get_images
html
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by kesdoputr** [comment]
同一樓，已更新到最新版

http://tw.manhuagui.com/comic/4739/

Start download 妄想學生會
Start downloading 妄想學生會
total 354 episode.
Downloading ep 第462回
Traceback (most recent call last):
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 582, in
 error_loop
    process()
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 532, in
 download
    crawler.init()
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 373, in
 init
    self.init_images(self.ep.current_page - 1)
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 380, in
 init_images
    self.get_images()
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 499, in
 get_images
    self.ep.current_url
  File "c:\python\lib\site-packages\comiccrawler\mods\seemh.py", line 74, in get
_images
    html
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by eight04** [comment]
於 2018.3.9 修正。
