### ISSUE TITLE
manhuagui.com下载失效

### ISSUE THREAD

**Issue by zcy85611** [eight04/ComicCrawler#105]
之前一直能够成功下载，最近再尝试下载的时候，出现如下的错误信息，其他几个漫画网站我测试过，还能够正常下载，可以排除系统和软件问题，请作者帮助看一下是否需要更新模块，谢谢！

`Start download 幽游白书
Start downloading 幽游白书
total 36 episode.
Downloading ep 第01卷
Traceback (most recent call last):
  File "c:\users\skygu\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\core\__init__.py", line 581, in error_loop
    process()
  File "c:\users\skygu\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\core\__init__.py", line 531, in download
    crawler.init()
  File "c:\users\skygu\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\core\__init__.py", line 372, in init
    self.init_images(self.ep.current_page - 1)
  File "c:\users\skygu\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\core\__init__.py", line 379, in init_images
    self.get_images()
  File "c:\users\skygu\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\core\__init__.py", line 498, in get_images
    self.ep.current_url
  File "c:\users\skygu\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\mods\seemh.py", line 74, in get_images
    html
AttributeError: 'NoneType' object has no attribute 'group'`

**Comment by eight04** [comment]
你使用的版本是？

**Comment by zcy85611** [comment]
我一开始用的是1.30日的版本，后来发现不行，就更新到3.9日的版本，仍然不行，都是上面的那段提示

**Comment by eight04** [comment]
網址是？

**Comment by zcy85611** [comment]
http://www.manhuagui.com/

**Comment by eight04** [comment]
是說任務的網址

**Comment by zcy85611** [comment]
http://www.manhuagui.com/comic/4113/

除了这个，我还试了这个网站其他几个，都是一样的提示

**Comment by eight04** [comment]
我這邊正常︰
```
Start analyzing http://www.manhuagui.com/comic/4113/
Session saved
Analyzing success!
Start download 幽游白书
Start downloading 幽游白书
total 36 episode.
Downloading ep 第01卷
Downloading 第01卷 page 1: http://i.hamreus.com/ps2/y/yybs/01/YU01_000.jpg.webp?
cid=36229&md5=X0FtwEqT30ptK3LzFWaEaQ

Session saved
Stop downloading
停止下載
Downloading 第01卷 page 2: http://i.hamreus.com/ps2/y/yybs/01/YU01_001.png.webp?
cid=36229&md5=X0FtwEqT30ptK3LzFWaEaQ

Session saved
```
確定版本是 2018.3.9 嗎？執行 `comiccrawler --version` 的結果為何？

**Comment by zcy85611** [comment]
知道原因了，我下载了3.9日的，但是没有更新，所以还是1.30的，现在更新完了以后，就正常了，感谢！
