### ISSUE TITLE
请求添加新的mod和提交报错，谢谢！

### ISSUE THREAD

**Issue by starobots** [eight04/ComicCrawler#106]
1、请求新添加这个网站的mod。
http://www.manhuadb.com

2、seemh出错。
终端显示报错。
网页里显示“点击继续阅读”，点击之后就可以看得到。
点击之后cookie多一个键值：isAdult = 1
http://tw.manhuagui.com/comic/4578/195883.html
下载的时候报错没保存下来。

3、之后是这个问题。
Downloading ep 第13卷
Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\lib\site-packages\comiccrawler\core\__init__.py", line 582, in error_loop
    process()
  File "c:\program files (x86)\python36-32\lib\site-packages\comiccrawler\core\__init__.py", line 532, in download
    crawler.init()
  File "c:\program files (x86)\python36-32\lib\site-packages\comiccrawler\core\__init__.py", line 373, in init
    self.init_images(self.ep.current_page - 1)
  File "c:\program files (x86)\python36-32\lib\site-packages\comiccrawler\core\__init__.py", line 380, in init_images
    self.get_images()
  File "c:\program files (x86)\python36-32\lib\site-packages\comiccrawler\core\__init__.py", line 499, in get_images
    self.ep.current_url
  File "c:\program files (x86)\python36-32\lib\site-packages\comiccrawler\mods\seemh.py", line 88, in get_images
    with VM(js) as vm:
  File "c:\program files (x86)\python36-32\lib\site-packages\node_vm2\__init__.py", line 63, in __enter__
    self.create()
  File "c:\program files (x86)\python36-32\lib\site-packages\node_vm2\__init__.py", line 78, in create
    self.id = self.communicate(data)
  File "c:\program files (x86)\python36-32\lib\site-packages\node_vm2\__init__.py", line 99, in communicate
    raise VMError(data["error"])
node_vm2.VMError: SMH is not defined

最后非常感谢eight！

**Comment by eight04** [comment]
> 1、请求新添加这个网站的mod。
> http://www.manhuadb.com

理由是？

**Comment by starobots** [comment]
囧，我也不知道为啥。
之前用的dmzj，dm5删的太多了。汗汗总改名。
另外，汗汗改地址叫www.hhmmoo.com
精明眼改叫www.iieye.cc
暗暗漫画网现在不知道地址了。。
话说大佬能不能写个教程怎么写mod。。。

**Comment by eight04** [comment]
> 我也不知道为啥

Comic Crawler 不會沒有原因地去支援特定網站。通常會加入支援有以下原因︰

1. 該網站有別站沒有的資源
2. 該網站圖片解析度特別好，沒有水印等等
3. 該網站傳輸速度特別快

> 教程怎么写mod

哪種的教程？如果要學 Python，可以參考官方的教學文件︰https://docs.python.org/3/tutorial/index.html ；如果要瞭解如何撰寫 Comic Crawler 的模組，可以參考 README 中的範例，或者參考 mods 資料夾底下的各模組。README 中的範例在 config 的部份有點過時了，我更新一下。

**Comment by eight04** [comment]
> README 中的範例在 config 的部份有點過時了

已修正

**Comment by eight04** [comment]
於 2018.3.18 修正。如果有需要 http://www.manhuadb.com/ 再開新 issue。

**Comment by starobots** [comment]
谢谢eight及时更新！

还有问题2，还是这个链接：http://tw.manhuagui.com/comic/4578/195883.html
现在直接显示download complete，实际并没有下载。
Start downloading 猎魔兽女
total 17 episode.
Downloading ep 第13卷
Episode download complete!
Downloading ep 第14卷
Episode download complete!
Downloading ep 第15卷
Episode download complete!
Downloading ep 第16卷
Episode download complete!
Downloading ep 第17卷
Episode download complete!

网页里面显示根据法律要求屏蔽漫画。
用国内的ip看不了，切换欧洲ip，会有一个年满18岁点击继续查看。
点完后，就在cookie里面加一条isAdult = 1，然后就可以继续看。
不过用crawler，应该是没有cookie的关系，就显示已经下载完成。
用欧洲ip也抓不到图片地址。 

以前屏蔽功能是在cookie里面country = cn是屏蔽状态，country = us就是解除屏蔽状态。
cookie不影响抓图。现在机制改了。

再次感谢！

**Comment by eight04** [comment]
我這邊直接爬是沒有問題。你能測試加入 cookie 後的效果嗎？找到 seemh.py 後在第 20 行加上︰
```py
cookie = {
  "isAdult": "1"
}
```

**Comment by starobots** [comment]
额，我这换去欧洲的ip就能正常用正常下载，不用改cookie了。

按照上面说的改完之后就是这样的：
Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python36-32\Scripts\comiccrawler.exe\__main__.py", line 9, in <module>
  File "c:\program files (x86)\python36-32\lib\site-packages\comiccrawler\__init__.py", line 58, in console_init
    main()
  File "c:\program files (x86)\python36-32\lib\site-packages\comiccrawler\gui\__init__.py", line 6, in main
    from .main_window import MainWindow
  File "c:\program files (x86)\python36-32\lib\site-packages\comiccrawler\gui\main_window.py", line 14, in <module>
    from ..mods import list_domain, get_module, load_config, domain_index
  File "c:\program files (x86)\python36-32\lib\site-packages\comiccrawler\mods\__init__.py", line 40, in <module>
    mods.add(import_module("comiccrawler.mods." + name))
  File "c:\program files (x86)\python36-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\program files (x86)\python36-32\lib\site-packages\comiccrawler\mods\seemh.py", line 19
    "isAdult": "1"
             ^
SyntaxError: invalid syntax

感谢eight！

**Comment by starobots** [comment]
囧，又试了一下，换成欧洲ip又可以正常用。。。
早上试着改过config，他返回的内容是这个。
```
Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python36-32\Scripts\comiccrawler.exe\__main__.py", line 9, in <module>
  File "c:\program files (x86)\python36-32\lib\site-packages\comiccrawler\__init__.py", line 58, in console_init
    main()
  File "c:\program files (x86)\python36-32\lib\site-packages\comiccrawler\gui\__init__.py", line 6, in main
    from .main_window import MainWindow
  File "c:\program files (x86)\python36-32\lib\site-packages\comiccrawler\gui\main_window.py", line 14, in <module>
    from ..mods import list_domain, get_module, load_config, domain_index
  File "c:\program files (x86)\python36-32\lib\site-packages\comiccrawler\mods\__init__.py", line 40, in <module>
    mods.add(import_module("comiccrawler.mods." + name))
  File "c:\program files (x86)\python36-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\program files (x86)\python36-32\lib\site-packages\comiccrawler\mods\seemh.py", line 19
    "isAdult": "1"
             ^
SyntaxError: invalid syntax
```

最后谢谢eight！
