### ISSUE TITLE
有问题

### ISSUE THREAD

**Issue by coremaya** [eight04/ComicCrawler#111]
![image](https://user-images.githubusercontent.com/20692119/39530072-b9d7d830-4e5a-11e8-85ac-ea06e56aa8b1.png)

**Comment by coremaya** [comment]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\comiccrawler\core\__init__.py", line 598, in analyze
    Analyzer(mission).analyze()
  File "d:\python\lib\site-packages\comiccrawler\core\__init__.py", line 709, in analyze
    self.do_analyze()
  File "d:\python\lib\site-packages\comiccrawler\core\__init__.py", line 736, in do_analyze
    self.html, self.mission.url)
  File "d:\python\lib\site-packages\comiccrawler\mods\dmzj.py", line 19, in get_title
    return re.search("<h1>(.+?)</h1>", html).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by Zivch** [comment]
大大好，
順著這個post另外舉報一個狀況。
最近好像抓不到dm5網站上的更新(像http://www.dm5.com/manhua-darling-in-the-franxx/ )，
或是有些區分成「連載」和「卷」的話就會讀不到連載的部份(像http://www.dm5.com/manhua-gebulinshashou/ )。
煩請大大有空可以幫忙查看和更新，謝謝。

**Comment by eight04** [comment]
@coremaya 請附上出錯的網址。另外你的圖片上，出錯的是 ACGN.cc，而錯誤代碼中出錯的是 dmzj。

@Zivch #112

**Comment by coremaya** [comment]
哪个网站都是这个错误 是不是需要什么运行库

**Comment by coremaya** [comment]
@eight04

**Comment by coremaya** [comment]
https://manhua.dmzj.com/yiquanchaoren/68296.shtml#@page=1

**Comment by coremaya** [comment]
![image](https://user-images.githubusercontent.com/20692119/39561972-a3740a24-4edb-11e8-8f51-cb03f869fe4b.png)

**Comment by coremaya** [comment]
我自己操作失误，感谢大大
