### ISSUE TITLE
Failed to analyze senmanga

### ISSUE THREAD

**Issue by eight04** [eight04/ComicCrawler#129]
e.g. https://raw.senmanga.com/Anagle_Mole
```
Start analyzing http://www.pixiv.net/member_illust.php?id=8315373
Traceback (most recent call last):
  File "d:\dev\comiccrawler\comiccrawler\download_manager.py", line 152, in anal
yze_thread
    Analyzer(mission).analyze()
  File "d:\dev\comiccrawler\comiccrawler\analyzer.py", line 56, in analyze
    self.do_analyze()
  File "d:\dev\comiccrawler\comiccrawler\analyzer.py", line 83, in do_analyze
    self.html, self.mission.url)
  File "d:\dev\comiccrawler\comiccrawler\mods\senmanga.py", line 16, in get_titl
e
    return re.search(r'<h1 itemprop="name"><a[^>]*>([^<]+)', html).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by eight04** [comment]
Fixed in 2018.6.21.
