### ISSUE TITLE
受漫畫網址更換&解析出錯

### ISSUE THREAD

**Issue by IthildinX** [eight04/ComicCrawler#133]
受漫畫的網址改為http://www.33am.cn/
用原網址目前會自動跳轉，但下載漫畫時就會出錯無法下載，
試著使用瀏覽器前往解析出來的圖片連結會顯示403無權限

漫畫網址:
http://www.33am.cn/gushi/2026/

CMD訊息:
Start download 百鍊成神
Start downloading 百鍊成神
total 597 episode.
Downloading ep 第241话 顺藤摸瓜
Downloading 第241话 顺藤摸瓜 page 1: http://www.xznj120.com/statics/pic/?p=http%3A//res.img.pufei.net/2018/07/06/17/05af06a07a.jpg/0&picid=2026

Traceback (most recent call last):
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\core\__init__.py", line 582, in error_loop
    process()
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\core\__init__.py", line 554, in download
    crawler.download_image()
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\core\__init__.py", line 415, in download_image
    raise Exception("Can't determine file type.")
Exception: Can't determine file type.
Downloading 第241话 顺藤摸瓜 page 1: http://www.xznj120.com/statics/pic/?p=http%3A//res.img.pufei.net/2018/07/06/17/05af06a07a.jpg/0&picid=2026

Traceback (most recent call last):
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\core\__init__.py", line 582, in error_loop
    process()
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\core\__init__.py", line 554, in download
    crawler.download_image()
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\core\__init__.py", line 415, in download_image
    raise Exception("Can't determine file type.")
Exception: Can't determine file type.

第一頁圖片目前的位址變成如下:
http://www.33am.cn/qingtiancms_wap/upload2/cache/2026/2018_2f07_2f06_2f17_2f05af06a07a_jpg_2f0.jpg

**Comment by eight04** [comment]
我大概要一段時間後才能修這個。

**Comment by eight04** [comment]
於 2018.7.18 加入 www.33am.cn

**Comment by IthildinX** [comment]
目前受漫畫解析又會出現錯誤

漫畫網址
http://www.36rm.cn/gushi/2271/

CMD訊息

Start download 妖精种植手册
Start downloading 妖精种植手册
total 356 episode.
Downloading ep 319-哥哥来啦~
Downloading 319-哥哥来啦~ page 1: http://www.33am.cn/statics/pic/?p=http%3A//res.img.pufei.net/2018/05/25/14/568e8937a3.jpg&picid=2271

Traceback (most recent call last):
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\crawler.py", line 323, in error_loop
    process()
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\crawler.py", line 295, in download
    crawler.download_image()
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\crawler.py", line 93, in download_image
    raise Exception("Can't determine file type.")
Exception: Can't determine file type.

**Comment by eight04** [comment]
我輸入 http://www.36rm.cn/gushi/2271/ 會顯示不支援的網址。

如果是指網站換網域的話請開一個新 issue

**Comment by IthildinX** [comment]
抱歉一開始沒注意到網域更換，解析器裡面用原漫畫網址也有讀到章節，沒發現換了
我重新整理發一篇新的
