### ISSUE TITLE
当检查更新发生错误时会无限检查更新

### ISSUE THREAD

**Issue by petronny** [eight04/ComicCrawler#15]
我既有需要挂代理的才能访问的站点，也有可以直接访问的站点。

有时为了加快速度，访问的不需要代理的站点时我不会挂代理。
这就会导致其他需要挂代理的检查更新时会发生错误。

我觉得应该是更新错误了就结束了就好，不过会不停的重复检查那些错误的部分的更新
之后就会无限输出
```
Traceback (most recent call last):
  File "/home/petron/.local/lib/python3.5/site-packages/comiccrawler-2016.6.30-py3.5.egg/comiccrawler/core/__init__.py", line 423, in analyze
    analyze_info(mission, mission.module)
  File "/home/petron/.local/lib/python3.5/site-packages/comiccrawler-2016.6.30-py3.5.egg/comiccrawler/core/__init__.py", line 473, in analyze_info
    eps = downloader.get_episodes(html, url)
  File "/home/petron/.local/lib/python3.5/site-packages/comiccrawler-2016.6.30-py3.5.egg/comiccrawler/mods/dm5.py", line 30, in get_episodes
    html = html[html.index("cbc_1"):]
ValueError: substring not found
```

我故意把网络断掉也可以重现这个问题

**Comment by eight04** [comment]
在 2016.6.25 後的版本，會把檢查錯誤的任務移至列表底部。並且在連續十次錯誤後停止檢查並報錯。

不過我發現其它的 bug︰

1. 檢查更新失敗視窗會凍結五秒
2. 停止檢查時跳出的錯誤訊息顯示不正確

**Comment by eight04** [comment]
上面兩個問題已於 2016.7.1 修正

**Comment by petronny** [comment]
但是我现在检查更新只会检查第一个。。
剩下的一直处于准备分析状态。。

**Comment by eight04** [comment]
意思是說第一個發生錯誤後不會被降到最底下嗎？
那麼錯誤發生十次後有停止檢查更新嗎？

**Comment by petronny** [comment]
不是，就是只检查第一个的。
第一个成功就结束了，别的不检查了

**Comment by eight04** [comment]
已於 2016.7.2 修正
