### ISSUE TITLE
今天更新後 pxiv 似乎依然還是壞的

### ISSUE THREAD

**Issue by bluelovers** [eight04/ComicCrawler#153]
https://www.pixiv.net/member_illust.php?id=2034188

![default](https://user-images.githubusercontent.com/167966/45930623-33822680-bf95-11e8-8da5-70853826f96a.png)

```
Update checking done
Start analyzing https://www.pixiv.net/member_illust.php?id=2034188
Warning: get_episodes returns an empty list
Error occurred in listener:
Traceback (most recent call last):
  File "C:\Python\Python36-32\lib\site-packages\worker\__init__.py", line 153, in process_event
    listener.callback(event)
  File "C:\Python\Python36-32\lib\site-packages\worker\__init__.py", line 401, in _
    callback(*args, **kwargs)
  File "C:\Python\Python36-32\lib\site-packages\comiccrawler\gui\select_episodes.py", line 154, in select_episodes
    on_closed=on_closed
  File "C:\Python\Python36-32\lib\site-packages\comiccrawler\gui\select_episodes.py", line 23, in __init__
    super().__init__(parent, title, on_closed=on_closed)
  File "C:\Python\Python36-32\lib\site-packages\comiccrawler\gui\dialog.py", line 20, in __init__
    self.create_body()
  File "C:\Python\Python36-32\lib\site-packages\comiccrawler\gui\select_episodes.py", line 110, in create_body
    height=cord[3],
TypeError: 'NoneType' object is not subscriptable
```

**Comment by eight04** [comment]
確定一下版本，在 CMD 執行 `comiccrawler --version`
