### ISSUE TITLE
[看漫画](www.manhuagui.com)支援异常，FileNotFoundError: [WinError 2] 系统找不到指定的文件

### ISSUE THREAD

**Issue by BianQue** [eight04/ComicCrawler#159]
## 版本
- Python 3.7.1
-  ComicCrawler v2018.10.24

## 日志
``` log
Start analyzing https://www.manhuagui.com/comic/17023/
Analyzing success!
Start download 关于我转生后成为史莱姆的那件事
Start downloading 关于我转生后成为史莱姆的那件事
total 58 episode.
Downloading ep 单话 第44回
Traceback (most recent call last):
  File "c:\users\zxhad\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\crawler.py", line 323, in error_loop
    process()
  File "c:\users\zxhad\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\crawler.py", line 273, in download
    crawler.init()
  File "c:\users\zxhad\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\crawler.py", line 51, in init
    self.init_images(self.ep.current_page - 1)
  File "c:\users\zxhad\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\crawler.py", line 58, in init_images
    self.get_images()
  File "c:\users\zxhad\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\crawler.py", line 177, in get_images
    self.ep.current_url
  File "c:\users\zxhad\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\mods\seemh.py", line 108, in get_images
    with VM(js) as vm:
  File "c:\users\zxhad\appdata\local\programs\python\python37\lib\site-packages\node_vm2\__init__.py", line 115, in __init__
    super().__init__(server)
  File "c:\users\zxhad\appdata\local\programs\python\python37\lib\site-packages\node_vm2\__init__.py", line 53, in __init__
    server = default_bridge()
  File "c:\users\zxhad\appdata\local\programs\python\python37\lib\site-packages\node_vm2\__init__.py", line 35, in default_bridge
    DEFAULT_BRIDGE = VMServer().start()
  File "c:\users\zxhad\appdata\local\programs\python\python37\lib\site-packages\node_vm2\__init__.py", line 389, in start
    self.process = Popen(args, bufsize=0, stdin=PIPE, stdout=PIPE)
  File "c:\users\zxhad\appdata\local\programs\python\python37\lib\subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "c:\users\zxhad\appdata\local\programs\python\python37\lib\subprocess.py", line 1172, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
Stop downloading
停止下載
```

**Comment by eight04** [comment]
你有裝 Node.js 嗎？https://github.com/eight04/ComicCrawler#install-nodejs
