### ISSUE TITLE
友繪漫畫下載時出錯

### ISSUE THREAD

**Issue by IthildinX** [eight04/ComicCrawler#161]
解析章節沒有問題 但下載會出現錯誤
漫畫網址: http://m.wuyouhui.net/mingxing/zhongshengzhiweishuiyingdi/
錯誤CMD訊息:

Start download 重生只为追影帝
Start downloading 重生只为追影帝
total 141 episode.
Downloading ep 128.被困住了
Traceback (most recent call last):
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\crawler.py", line 323, in error_loop
    process()
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\crawler.py", line 273, in download
    crawler.init()
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\crawler.py", line 51, in init
    self.init_images(self.ep.current_page - 1)
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\crawler.py", line 58, in init_images
    self.get_images()
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\crawler.py", line 177, in get_images
    self.ep.current_url
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\mods\xznj120.py", line 45, in get_images
    return [urljoin(url, i) for i in eval(code)]
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\node_vm2\__init__.py", line 26, in eval
    return vm.run(code)
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\node_vm2\__init__.py", line 129, in run
    return self.communicate({"action": "run", "code": code})
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\node_vm2\__init__.py", line 99, in communicate
    raise VMError(data["error"])
node_vm2.VMError: base64_decode is not defined

**Comment by eight04** [comment]
Fixed in 2018.11.18.
