### ISSUE TITLE
古風漫畫網域更換

### ISSUE THREAD

**Issue by IthildinX** [eight04/ComicCrawler#176]
原網域: www.gufengmh.com
現網域: www.gufengmh8.com

此外連線由http://變成https:// 原先的pool檔案內容需要更新

**Comment by IthildinX** [comment]
手動增加www.gufengmh8.com網域後，下載仍會出錯
看解析到的圖片網址還是舊網域，然後會發生404下載錯誤或是下載到古風漫畫網的標題圖 https://i.imgur.com/cRufayj.png 

以下舉例
漫畫網址
https://www.gufengmh8.com/manhua/wodedabaojian/

CMD內容

Downloading ep 第八十四话 一出好戏

Downloading 第八十四话 一出好戏 page 1: http://res.gufengmh.com/images/comic/420/839274/1552106870L_Id0ooLvKIsCK9V.jpg

Downloading 第八十四话 一出好戏 page 2: http://res.gufengmh.com/images/comic/420/839274/15521068695eF5kgz-fGYH0G4b.jpg

Downloading 第八十四话 一出好戏 page 3: http://res.gufengmh.com/images/comic/420/839274/1552106867DfHqlyOuzlVE-iq-.jpg

Traceback (most recent call last):
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\crawler.py", line 325, in error_loop
    process()
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\crawler.py", line 297, in download
    crawler.download_image()
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\crawler.py", line 81, in download_image
    self.image.url, referer=self.ep.current_url)
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\module_grabber.py", line 27, in img
    **kwargs
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\grabber.py", line 209, in grabimg
    return ImgResult(grabber(*args, **kwargs))
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\grabber.py", line 106, in grabber
    r = await_(do_request, s, url, params, proxies, method, data, retry)
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\worker\__init__.py", line 905, in wrapped
    return f(*args, **kwargs)
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\worker\__init__.py", line 927, in await_
    return async_(callback, *args, **kwargs).get()
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\worker\__init__.py", line 682, in get
    raise err
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\worker\__init__.py", line 474, in wrap_worker
    self.ret = self.worker(*args, **kwargs)
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\grabber.py", line 132, in do_request
    r.raise_for_status()
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://res.gufengmh.com/images/comic/420/839274/1552106867DfHqlyOuzlVE-iq-.jpg
