### ISSUE TITLE
看漫畫 解析時SSL錯誤

### ISSUE THREAD

**Issue by IthildinX** [eight04/ComicCrawler#177]
舉其中一個漫畫為例

漫畫網址 https://tw.manhuagui.com/comic/30367/
錯誤訊息

Start analyzing https://tw.manhuagui.com/comic/30367/
Thread crashed: <function DownloadManager.start_analyze.<locals>.analyze_thread at 0x00000162229A69D8>
Traceback (most recent call last):
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\urllib3\connectionpool.py", line 595, in urlopen
    self._prepare_proxy(conn)
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\urllib3\connectionpool.py", line 816, in _prepare_proxy
    conn.connect()
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\urllib3\connection.py", line 326, in connect
    ssl_context=context)
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\urllib3\util\ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\ssl.py", line 814, in __init__
    self.do_handshake()
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\urllib3\util\retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='tw.manhuagui.com', port=443): Max retries exceeded with url: /comic/30367/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\worker\__init__.py", line 474, in wrap_worker
    self.ret = self.worker(*args, **kwargs)
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\download_manager.py", line 152, in analyze_thread
    Analyzer(mission).analyze()
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\analyzer.py", line 57, in analyze
    self.do_analyze()
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\analyzer.py", line 80, in do_analyze
    self.html = self.grabber.html(self.mission.url, retry=True)
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\module_grabber.py", line 17, in html
    **kwargs
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\grabber.py", line 152, in grabhtml
    r = grabber(*args, **kwargs)
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\grabber.py", line 106, in grabber
    r = await_(do_request, s, url, params, proxies, method, data, retry)
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\worker\__init__.py", line 905, in wrapped
    return f(*args, **kwargs)
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\worker\__init__.py", line 927, in await_
    return async_(callback, *args, **kwargs).get()
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\worker\__init__.py", line 682, in get
    raise err
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\worker\__init__.py", line 474, in wrap_worker
    self.ret = self.worker(*args, **kwargs)
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\grabber.py", line 120, in do_request
    data=data, proxies=proxies)
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\requests\adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='tw.manhuagui.com', port=443): Max retries exceeded with url: /comic/30367/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))

**Comment by IthildinX** [comment]
騰訊 (ac.qq.com) 也會有類似的SSL錯誤訊息
但同樣使用https的動漫之家就沒問題.....

**Comment by IthildinX** [comment]
檢查設定後懷疑是hinet proxy問題 關閉後解析似乎正常
