### ISSUE TITLE
請問 FB 下載功能 是 未完成 還是 不支援相簿?

### ISSUE THREAD

**Issue by bluelovers** [eight04/ComicCrawler#184]
測試網址
```
https://www.facebook.com/pg/graphicartsornament/photos/?tab=album&album_id=525566031301902&__tn__=-UCH-R
```

```
Start download Graphic Arts . Эскизы / Графика / Орнаменты - 相片 | Facebook (?tab=album&album_id=525566031301902&__tn__=-UCH-R)
Start downloading Graphic Arts . Эскизы / Графика / Орнаменты - 相片 | Facebook (?tab=album&album_id=525566031301902&__tn__=-UCH-R)
total 1 episode.
Downloading ep image
Traceback (most recent call last):
  File "c:\python37-32\lib\site-packages\comiccrawler\crawler.py", line 323, in error_loop
    process()
  File "c:\python37-32\lib\site-packages\comiccrawler\crawler.py", line 274, in download
    crawler.init()
  File "c:\python37-32\lib\site-packages\comiccrawler\crawler.py", line 51, in init
    self.init_images(self.ep.current_page - 1)
  File "c:\python37-32\lib\site-packages\comiccrawler\crawler.py", line 58, in init_images
    self.get_images()
  File "c:\python37-32\lib\site-packages\comiccrawler\crawler.py", line 176, in get_images
    self.ep.current_url
  File "c:\python37-32\lib\site-packages\comiccrawler\mods\facebook.py", line 50, in get_images
    fbset, fbid = get_url_info(url)
  File "c:\python37-32\lib\site-packages\comiccrawler\mods\facebook.py", line 47, in get_url_info
    return query["set"], query["fbid"]
KeyError: 'set'
Stop downloading
停止下載
```

---

另外 希望能增加在 pixiv 增加新的連結時 不詢問勾選 的選項

**Comment by eight04** [comment]
支援的 URL 形式為
```
https://www.facebook.com/graphicartsornament/photos/a.525566031301902/525566231301882/?type=3&theater
```
不過現在有 bug，以致於下載一頁就停了。已於 #185 修正。

> 另外 希望能增加在 pixiv 增加新的連結時 不詢問勾選 的選項

如果你使用批次分析，就不會跳出詢問對話框。順帶一提，按 Enter 鍵相當於點對話框的「確認」鈕。

**Comment by bluelovers** [comment]
我直接複製你的網址 但是似乎也是失敗

```
C:\Program Files (Portable)\ConsoleZ>comiccrawler --version
2019.3.26
```

```
Start analyzing https://www.facebook.com/graphicartsornament/photos/a.525566031301902/525566231301882/?type=3&theater
Analyzing success!
Start download Graphic Arts . Эскизы / Графика /... - Graphic Arts . Эскизы / Графика / Орнаменты | Facebook (a.525566031301902)
Start downloading Graphic Arts . Эскизы / Графика /... - Graphic Arts . Эскизы / Графика / О рнаменты | Facebook (a.525566031301902)
total 1 episode.
Downloading ep image
Traceback (most recent call last):
  File "c:\python37-32\lib\site-packages\comiccrawler\crawler.py", line 323, in error_loop
    process()
  File "c:\python37-32\lib\site-packages\comiccrawler\crawler.py", line 274, in download
    crawler.init()
  File "c:\python37-32\lib\site-packages\comiccrawler\crawler.py", line 51, in init
    self.init_images(self.ep.current_page - 1)
  File "c:\python37-32\lib\site-packages\comiccrawler\crawler.py", line 58, in init_images
    self.get_images()
  File "c:\python37-32\lib\site-packages\comiccrawler\crawler.py", line 176, in get_images
    self.ep.current_url
  File "c:\python37-32\lib\site-packages\comiccrawler\mods\facebook.py", line 51, in get_images
    fb_dtsg = re.search('name="fb_dtsg" value="([^"]+)', html).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
Stop downloading
停止下載
```

**Comment by eight04** [comment]
你有登入嗎？

bluelovers <notifications@github.com> 於 2019年3月26日 週二 下午8:01寫道：

**Comment by bluelovers** [comment]
@eight04  噗 你回得太快 我發完文之後 沒多久就想到 難道是多了登入功能 而且刪了留言 lol
