### ISSUE TITLE
manhuagui error 403

### ISSUE THREAD

**Issue by msp26** [eight04/ComicCrawler#201]
When using a manhuagui URL, the downloader can't access any pages past page 1.
`Downloading 单行本 第01卷 page 1: http://us.hamreus.com/ps4/t/屠龙圣传[增田晴彦]/vol_01/seemh-001-59e7.jpg.webp?cid=154153&md5=cJjV9ctbFlVbyjLSSroUeg

Traceback (most recent call last):
  File "C:\Users\Manav\PycharmProjects\untitled\venv\lib\site-packages\comiccrawler\crawler.py", line 323, in error_loop
    process()
  File "C:\Users\Manav\PycharmProjects\untitled\venv\lib\site-packages\comiccrawler\crawler.py", line 296, in download
    crawler.download_image()
  File "C:\Users\Manav\PycharmProjects\untitled\venv\lib\site-packages\comiccrawler\crawler.py", line 81, in download_image
    self.image.url, referer=self.ep.current_url)
  File "C:\Users\Manav\PycharmProjects\untitled\venv\lib\site-packages\comiccrawler\module_grabber.py", line 27, in img
    **kwargs
  File "C:\Users\Manav\PycharmProjects\untitled\venv\lib\site-packages\comiccrawler\grabber.py", line 209, in grabimg
    return ImgResult(grabber(*args, **kwargs))
  File "C:\Users\Manav\PycharmProjects\untitled\venv\lib\site-packages\comiccrawler\grabber.py", line 106, in grabber
    r = await_(do_request, s, url, params, proxies, method, data, retry)
  File "C:\Users\Manav\PycharmProjects\untitled\venv\lib\site-packages\worker\__init__.py", line 905, in wrapped
    return f(*args, **kwargs)
  File "C:\Users\Manav\PycharmProjects\untitled\venv\lib\site-packages\worker\__init__.py", line 927, in await_
    return async_(callback, *args, **kwargs).get()
  File "C:\Users\Manav\PycharmProjects\untitled\venv\lib\site-packages\worker\__init__.py", line 682, in get
    raise err
  File "C:\Users\Manav\PycharmProjects\untitled\venv\lib\site-packages\worker\__init__.py", line 474, in wrap_worker
    self.ret = self.worker(*args, **kwargs)
  File "C:\Users\Manav\PycharmProjects\untitled\venv\lib\site-packages\comiccrawler\grabber.py", line 132, in do_request
    r.raise_for_status()
  File "C:\Users\Manav\PycharmProjects\untitled\venv\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://us.hamreus.com/ps4/t/%E5%B1%A0%E9%BE%99%E5%9C%A3%E4%BC%A0%5B%E5%A2%9E%E7%94%B0%E6%99%B4%E5%BD%A6%5D/vol_01/seemh-001-59e7.jpg.webp?cid=154153&md5=cJjV9ctbFlVbyjLSSroUeg`

**Comment by eight04** [comment]
我這裡測試正常

**Comment by IthildinX** [comment]
漫畫櫃同IP大量存取(刷新列表/下載)的時候會被ban一陣子，HTTP錯誤403

**Comment by eight04** [comment]
曾經有人回報過 manhuagui 會擋大量連線，但那時指的是 www.manhuagui.com 的頁面，而非圖片伺服器（https://github.com/eight04/ComicCrawler/pull/135 ）。

如果圖片下載失敗的原因的確是伺服器在擋，那麼可能也得把圖片伺服器加入 cooldown。

**Comment by IthildinX** [comment]
圖片伺服器可能也會擋，曾經遇過在下載已經解析好章節有更新的漫畫，下載時也是出現這個HTTP403

**Comment by eight04** [comment]
的確有不同的 server。Comic Crawler 在遇到下載失敗時會自動換到一個新的 server︰
https://github.com/eight04/ComicCrawler/blob/d00659d165b29620731a5e29900cddcccef3c17c/comiccrawler/mods/seemh.py#L158-L166
