### ISSUE TITLE
騰訊漫畫下載出錯

### ISSUE THREAD

**Issue by IthildinX** [eight04/ComicCrawler#213]
持續了幾天，看錯誤訊息不像是網路問題，可能網頁又有改版
舉例如下

漫畫網址:
https://ac.qq.com/Comic/comicInfo/id/638790

CMD訊息:
Start downloading 鬥羅大陸4終極鬥羅
total 64 episode.
Downloading ep 93 - 斗罗大陆4终极斗罗：大魔王授课
Traceback (most recent call last):
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\crawler.py", line 323, in error_loop
    process()
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\crawler.py", line 274, in download
    crawler.init()
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\crawler.py", line 51, in init
    self.init_images(self.ep.current_page - 1)
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\crawler.py", line 58, in init_images
    self.get_images()
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\crawler.py", line 176, in get_images
    self.ep.current_url
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\mods\qq.py", line 40, in get_images
    view_js = re.search('src="([^"]+?page\.chapter\.view[^"]+?\.js[^"]+)', html).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by eight04** [comment]
Fixed in 2019.8.19.
