### ISSUE TITLE
请教eight，运行命令的时候出现这个问题。

### ISSUE THREAD

**Issue by starobots** [eight04/ComicCrawler#214]
命令行运行出现这个错误，gui无法启动。
删掉view.json，可以启动gui。

C:\Users\starbot>comiccrawler gui
Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python36-32\Scripts\comiccrawler.exe\__main__.py", line 9, in <module>
  File "c:\program files (x86)\python36-32\lib\site-packages\comiccrawler\__init__.py", line 58, in console_init
    main()
  File "c:\program files (x86)\python36-32\lib\site-packages\comiccrawler\gui\__init__.py", line 7, in main
    MainWindow()
  File "c:\program files (x86)\python36-32\lib\site-packages\comiccrawler\gui\main_window.py", line 505, in __init__
    self.update_table(mission_manager.view)
  File "c:\program files (x86)\python36-32\lib\site-packages\comiccrawler\gui\main_window.py", line 625, in update_table
    "name": safe_tk(mission.title),
  File "c:\program files (x86)\python36-32\lib\site-packages\comiccrawler\gui\core.py", line 28, in safe_tk
    return re.sub(r"[^\u0000-\uFFFF]", "_", text)
  File "c:\program files (x86)\python36-32\lib\re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object

**Comment by eight04** [comment]
看起來有個任務的名字出了問題，你刪掉 view.json 相當於把任務列表清空，所以就沒有錯誤了。
