### ISSUE TITLE
deviantart 無法下載

### ISSUE THREAD

**Issue by bluelovers** [eight04/ComicCrawler#225]
![image](https://user-images.githubusercontent.com/167966/67522135-c5032100-f6de-11e9-893f-2ccc6da4ceba.png)

```
Start analyzing https://www.deviantart.com/tahra
Thread crashed: <function DownloadManager.start_analyze.<locals>.analyze_thread at 0x03BC00C0>
Traceback (most recent call last):
  File "c:\python37-32\lib\site-packages\worker\__init__.py", line 474, in wrap_worker
    self.ret = self.worker(*args, **kwargs)
  File "c:\python37-32\lib\site-packages\comiccrawler\download_manager.py", line 152, in analyze_thread
    Analyzer(mission).analyze()
  File "c:\python37-32\lib\site-packages\comiccrawler\analyzer.py", line 57, in analyze
    self.do_analyze()
  File "c:\python37-32\lib\site-packages\comiccrawler\analyzer.py", line 84, in do_analyze
    self.html, self.mission.url)
  File "c:\python37-32\lib\site-packages\comiccrawler\mods\deviantart.py", line 28, in get_title
    return unescape(re.search("<title>(.+?)</title>", html).group(1))
AttributeError: 'NoneType' object has no attribute 'group'
Start analyzing https://www.deviantart.com/tahra
Thread crashed: <function DownloadManager.start_analyze.<locals>.analyze_thread at 0x07EF34B0>
Traceback (most recent call last):
  File "c:\python37-32\lib\site-packages\worker\__init__.py", line 474, in wrap_worker
    self.ret = self.worker(*args, **kwargs)
  File "c:\python37-32\lib\site-packages\comiccrawler\download_manager.py", line 152, in analyze_thread
    Analyzer(mission).analyze()
  File "c:\python37-32\lib\site-packages\comiccrawler\analyzer.py", line 57, in analyze
    self.do_analyze()
  File "c:\python37-32\lib\site-packages\comiccrawler\analyzer.py", line 84, in do_analyze
    self.html, self.mission.url)
  File "c:\python37-32\lib\site-packages\comiccrawler\mods\deviantart.py", line 28, in get_title
    return unescape(re.search("<title>(.+?)</title>", html).group(1))
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by eight04** [comment]
DeviantArt 改版，不過登入後可以切回舊版︰
![image](https://user-images.githubusercontent.com/1324510/67667066-0712b800-f9a8-11e9-9a0e-741df1b1c387.png)
https://www.deviantart.com/tahra/gallery/?catpath=/

**Comment by bluelovers** [comment]
https://www.deviantart.com/nathanrosario/gallery/all

現在沒有切回舊版的選項了
