### ISSUE TITLE
無法新增和更新pixiv搜尋的任務

### ISSUE THREAD

**Issue by x2443120** [eight04/ComicCrawler#237]
pixiv的介面又改版了的關係
無法新增任務只會跳:解析錯誤 'user'的訊息

Start analyzing https://www.pixiv.net/tags/HK416/artworks?mode=safe&blt=1000&bgt=%2A
Thread crashed: <function DownloadManager.start_analyze.<locals>.analyze_thread at 0x0CA68A08>
Traceback (most recent call last):
  File "c:\users\appdata\local\programs\python\python37-32\lib\site-packages\worker\__init__.py", line 474, in wrap_worker
    self.ret = self.worker(*args, **kwargs)
  File "c:\users\appdata\local\programs\python\python37-32\lib\site-packages\comiccrawler\download_manager.py", line 152, in analyze_thread
    Analyzer(mission).analyze()
  File "c:\users\appdata\local\programs\python\python37-32\lib\site-packages\comiccrawler\analyzer.py", line 57, in analyze
    self.do_analyze()
  File "c:\users\appdata\local\programs\python\python37-32\lib\site-packages\comiccrawler\analyzer.py", line 84, in do_analyze
    self.html, self.mission.url)
  File "c:\users\appdata\local\programs\python\python37-32\lib\site-packages\comiccrawler\mods\pixiv.py", line 53, in get_title
    return get_title_from_init_data(html, url)
  File "c:\users\appdata\local\programs\python\python37-32\lib\site-packages\comiccrawler\mods\pixiv.py", line 46, in get_title_from_init_data
    user = next(iter(init_data["preload"]["user"].values()))
KeyError: 'user'

**Comment by IthildinX** [comment]
更新則是會直接收到空白清單然後顯示完成

Start analyzing https://www.pixiv.net/member_illust.php?id=687572
Warning: get_episodes returns an empty list
Analyzing success!
Start analyzing https://www.pixiv.net/member_illust.php?id=5375435
Warning: get_episodes returns an empty list
Analyzing success!
Start analyzing https://www.pixiv.net/member_illust.php?id=448840
Warning: get_episodes returns an empty list
Analyzing success!
Start analyzing https://www.pixiv.net/member_illust.php?id=362833
Warning: get_episodes returns an empty list
Analyzing success!
