### ISSUE TITLE
dmzj無法下載

### ISSUE THREAD

**Issue by s4028600** [eight04/ComicCrawler#242]
https://manhua.dmzj.com/xiajiangqideta
```
Start download 就算这样，“步”还是靠了过来
Start downloading 就算这样，“步”还是靠了过来
total 61 episode.
Downloading ep 第01话
Traceback (most recent call last):
  File "c:\users\long\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\crawler.py", line 336, in error_loop
    process()
  File "c:\users\long\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\crawler.py", line 287, in download
    crawler.init()
  File "c:\users\long\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\crawler.py", line 51, in init
    self.init_images(self.ep.current_page - 1)
  File "c:\users\long\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\crawler.py", line 58, in init_images
    self.get_images()
  File "c:\users\long\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\crawler.py", line 186, in get_images
    self.ep.current_url
  File "c:\users\long\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\mods\dmzj.py", line 54, in get_images
    return get_images_eval(html, url)
  File "c:\users\long\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\mods\dmzj.py", line 72, in get_images_eval
    pages = eval(s + "; pages")
  File "c:\users\long\appdata\local\programs\python\python36\lib\site-packages\node_vm2\__init__.py", line 25, in eval
    with VM(**options) as vm:
  File "c:\users\long\appdata\local\programs\python\python36\lib\site-packages\node_vm2\__init__.py", line 115, in __init__
    super().__init__(server)
  File "c:\users\long\appdata\local\programs\python\python36\lib\site-packages\node_vm2\__init__.py", line 53, in __init__
    server = default_bridge()
  File "c:\users\long\appdata\local\programs\python\python36\lib\site-packages\node_vm2\__init__.py", line 35, in default_bridge
    DEFAULT_BRIDGE = VMServer().start()
  File "c:\users\long\appdata\local\programs\python\python36\lib\site-packages\node_vm2\__init__.py", line 389, in start
    self.process = Popen(args, bufsize=0, stdin=PIPE, stdout=PIPE)
  File "c:\users\long\appdata\local\programs\python\python36\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "c:\users\long\appdata\local\programs\python\python36\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系統找不到指定的檔案。
```

**Comment by eight04** [comment]
你有沒有安裝 Node.js?
https://github.com/eight04/ComicCrawler#install-nodejs

**Comment by s4028600** [comment]
> 你有沒有安裝 Node.js?
> https://github.com/eight04/ComicCrawler#install-nodejs

有
6.9.2的

**Comment by s4028600** [comment]
> 你有沒有安裝 Node.js?
> https://github.com/eight04/ComicCrawler#install-nodejs

有
6.9.2的

**Comment by eight04** [comment]
試著執行以下的指令︰
```
python --version && node --version && python -c "import vm2;vm2.eval('console.log(1)')"
```

**Comment by s4028600** [comment]
> 試著執行以下的指令︰
> 
> ```
> python --version && node --version && python -c "import vm2;vm2.eval('console.log(1)')"
> ```

他說node不是內部或外部......
所以我猜是環境變數有問題
更新node後解決
感謝
