### ISSUE TITLE
土豪漫畫SSL過期

### ISSUE THREAD

**Issue by IthildinX** [eight04/ComicCrawler#243]
舉例漫畫網址 https://www.tohomh123.com/gongjuefurendegongchawuyu/
分析時會出現以下錯誤，用瀏覽器看的時候可以手動選擇忽略繼續觀看，
不知道下載器有沒有辦法這樣強制忽略SSL過期的問題?

此外，已經存到圖書館的漫畫在檢查更新的時候會全部跳錯誤，累積太多錯誤還會造成檢查更新中斷，這部分有一點點小麻煩

Start analyzing https://www.tohomh123.com/gongjuefurendegongchawuyu/
Thread crashed: <function DownloadManager.start_analyze.<locals>.analyze_thread at 0x000001EC03845510>
Traceback (most recent call last):
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\urllib3\connection.py", line 344, in connect
    ssl_context=context)
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\urllib3\util\ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\ssl.py", line 853, in _create
    self.do_handshake()
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.tohomh123.com', port=443): Max retries exceeded with url: /gongjuefurendegongchawuyu/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1056)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\worker\__init__.py", line 474, in wrap_worker
    self.ret = self.worker(*args, **kwargs)
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\download_manager.py", line 152, in analyze_thread
    Analyzer(mission).analyze()
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\analyzer.py", line 57, in analyze
    self.do_analyze()
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\analyzer.py", line 80, in do_analyze
    self.html = self.grabber.html(self.mission.url, retry=True)
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\module_grabber.py", line 17, in html
    **kwargs
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\grabber.py", line 151, in grabhtml
    r = grabber(*args, **kwargs)
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\grabber.py", line 105, in grabber
    r = await_(do_request, s, url, proxies, retry, **kwargs)
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\worker\__init__.py", line 905, in wrapped
    return f(*args, **kwargs)
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\worker\__init__.py", line 927, in await_
    return async_(callback, *args, **kwargs).get()
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\worker\__init__.py", line 682, in get
    raise err
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\worker\__init__.py", line 474, in wrap_worker
    self.ret = self.worker(*args, **kwargs)
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\grabber.py", line 119, in do_request
    proxies=proxies, **kwargs)
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.tohomh123.com', port=443): Max retries exceeded with url: /gongjuefurendegongchawuyu/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1056)')))

**Comment by eight04** [comment]
……的確是可以關閉SSL檢查 https://stackoverflow.com/questions/15445981/how-do-i-disable-the-security-certificate-check-in-python-requests

這不太適合應用到所有的網站上。也許加個設定讓使用者手動去啟動比較好？不過我覺得最好的辦法是換個網站。

**Comment by IthildinX** [comment]
能轉移的我盡量使用別的來源的，不過有不少漫畫這邊才找的到免費並持續有更新，
希望可以在設定裡面弄個開關只針對特定網頁關閉?
這樣等他SSL修好也可以自己再修改設定應對就好
