### ISSUE TITLE
seiga.nicovideo.jp, Exception: Episode list is empty

### ISSUE THREAD

**Issue by Lee-lithium** [eight04/ComicCrawler#248]
seiga.nicovideo.jp 的解析器似乎失效了

目錄  https://seiga.nicovideo.jp/comic/33772
單章節頁面 https://seiga.nicovideo.jp/watch/mg375757

Start analyzing https://seiga.nicovideo.jp/comic/33772
Warning: get_episodes returns an empty list
Thread crashed: <function DownloadManager.start_analyze.<locals>.analyze_thread at 0x0662AA08>
Traceback (most recent call last):
  File "d:\c_drive\users\user\appdata\local\programs\python\python37-32\lib\site-packages\worker\__init__.py", line 474, in wrap_worker
    self.ret = self.worker(*args, **kwargs)
  File "d:\c_drive\users\user\appdata\local\programs\python\python37-32\lib\site-packages\comiccrawler\download_manager.py", line 152, in analyze_thread
    Analyzer(mission).analyze()
  File "d:\c_drive\users\user\appdata\local\programs\python\python37-32\lib\site-packages\comiccrawler\analyzer.py", line 57, in analyze
    self.do_analyze()
  File "d:\c_drive\users\user\appdata\local\programs\python\python37-32\lib\site-packages\comiccrawler\analyzer.py", line 86, in do_analyze
    self.analyze_pages()
  File "d:\c_drive\users\user\appdata\local\programs\python\python37-32\lib\site-packages\comiccrawler\analyzer.py", line 151, in analyze_pages
    raise Exception("Episode list is empty")
Exception: Episode list is empty

**Comment by eight04** [comment]
目前沒有支援 /comic，只支援 /user︰
https://github.com/eight04/ComicCrawler/blob/f4d4f9d461827e6f1b785a1ddba6168b5d3bd3ba/comiccrawler/mods/nico.py#L6

**Comment by Lee-lithium** [comment]
感謝您的回應 :)
