### ISSUE TITLE
无法下载ikanman

### ISSUE THREAD

**Issue by fireattack** [eight04/ComicCrawler#25]
http://www.ikanman.com/comic/1266/

```
C:\Users\Administrator>comiccrawler download http://www.ikanman.com/comic/1266/
Start analyzing http://www.ikanman.com/comic/1266/
Analyzing success!
Start downloading 黄昏流星群
total 36 episode.
Downloading ep 第01卷
Traceback (most recent call last):
  File "c:\python34\lib\site-packages\comiccrawler\core\__init__.py", line 428,
in error_loop
    process()
  File "c:\python34\lib\site-packages\comiccrawler\core\__init__.py", line 378,
in download
    crawler.init()
  File "c:\python34\lib\site-packages\comiccrawler\core\__init__.py", line 201,
in init
    self.init_images(self.ep.current_page - 1)
  File "c:\python34\lib\site-packages\comiccrawler\core\__init__.py", line 208,
in init_images
    self.get_images()
  File "c:\python34\lib\site-packages\comiccrawler\core\__init__.py", line 340,
in get_images
    self.ep.current_url
  File "c:\python34\lib\site-packages\comiccrawler\mods\seemh.py", line 97, in g
et_images
    return ctx.call("getFiles", path, files, host)
  File "c:\python34\lib\site-packages\execjs\_abstract_runtime_context.py", line
 37, in call
    return self._call(name, *args)
  File "c:\python34\lib\site-packages\execjs\_external_runtime.py", line 87, in
_call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=ident
ifier, args=args))
  File "c:\python34\lib\site-packages\execjs\_external_runtime.py", line 73, in
_eval
    return self.exec_(code)
  File "c:\python34\lib\site-packages\execjs\_abstract_runtime_context.py", line
 18, in exec_
    return self._exec_(source)
  File "c:\python34\lib\site-packages\execjs\_external_runtime.py", line 83, in
_exec_
    return self._extract_result(output)
  File "c:\python34\lib\site-packages\execjs\_external_runtime.py", line 165, in
 _extract_result
    raise exceptions.ProgramError(value)
execjs._exceptions.ProgramError: TypeError: 对象不支持此属性或方法
Traceback (most recent call last):
  File "c:\python34\lib\site-packages\comiccrawler\core\__init__.py", line 428,
in error_loop
    process()
  File "c:\python34\lib\site-packages\comiccrawler\core\__init__.py", line 378,
in download
    crawler.init()
  File "c:\python34\lib\site-packages\comiccrawler\core\__init__.py", line 201,
in init
    self.init_images(self.ep.current_page - 1)
  File "c:\python34\lib\site-packages\comiccrawler\core\__init__.py", line 208,
in init_images
    self.get_images()
  File "c:\python34\lib\site-packages\comiccrawler\core\__init__.py", line 340,
in get_images
    self.ep.current_url
  File "c:\python34\lib\site-packages\comiccrawler\mods\seemh.py", line 97, in g
et_images
    return ctx.call("getFiles", path, files, host)
  File "c:\python34\lib\site-packages\execjs\_abstract_runtime_context.py", line
 37, in call
    return self._call(name, *args)
  File "c:\python34\lib\site-packages\execjs\_external_runtime.py", line 87, in
_call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=ident
ifier, args=args))
  File "c:\python34\lib\site-packages\execjs\_external_runtime.py", line 73, in
_eval
    return self.exec_(code)
  File "c:\python34\lib\site-packages\execjs\_abstract_runtime_context.py", line
 18, in exec_
    return self._exec_(source)
  File "c:\python34\lib\site-packages\execjs\_external_runtime.py", line 83, in
_exec_
    return self._extract_result(output)
  File "c:\python34\lib\site-packages\execjs\_external_runtime.py", line 165, in
 _extract_result
    raise exceptions.ProgramError(value)
execjs._exceptions.ProgramError: TypeError: 对象不支持此属性或方法
Traceback (most recent call last):
  File "c:\python34\lib\site-packages\comiccrawler\core\__init__.py", line 428,
in error_loop
    process()
  File "c:\python34\lib\site-packages\comiccrawler\core\__init__.py", line 378,
in download
    crawler.init()
  File "c:\python34\lib\site-packages\comiccrawler\core\__init__.py", line 201,
in init
    self.init_images(self.ep.current_page - 1)
  File "c:\python34\lib\site-packages\comiccrawler\core\__init__.py", line 208,
in init_images
    self.get_images()
  File "c:\python34\lib\site-packages\comiccrawler\core\__init__.py", line 340,
in get_images
    self.ep.current_url
  File "c:\python34\lib\site-packages\comiccrawler\mods\seemh.py", line 97, in g
et_images
    return ctx.call("getFiles", path, files, host)
  File "c:\python34\lib\site-packages\execjs\_abstract_runtime_context.py", line
 37, in call
    return self._call(name, *args)
  File "c:\python34\lib\site-packages\execjs\_external_runtime.py", line 87, in
_call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=ident
ifier, args=args))
  File "c:\python34\lib\site-packages\execjs\_external_runtime.py", line 73, in
_eval
    return self.exec_(code)
  File "c:\python34\lib\site-packages\execjs\_abstract_runtime_context.py", line
 18, in exec_
    return self._exec_(source)
  File "c:\python34\lib\site-packages\execjs\_external_runtime.py", line 83, in
_exec_
    return self._extract_result(output)
  File "c:\python34\lib\site-packages\execjs\_external_runtime.py", line 165, in
 _extract_result
    raise exceptions.ProgramError(value)
execjs._exceptions.ProgramError: TypeError: 对象不支持此属性或方法
Traceback (most recent call last):
  File "c:\python34\lib\site-packages\comiccrawler\core\__init__.py", line 428,
in error_loop
    process()
  File "c:\python34\lib\site-packages\comiccrawler\core\__init__.py", line 378,
in download
    crawler.init()
  File "c:\python34\lib\site-packages\comiccrawler\core\__init__.py", line 201,
in init
    self.init_images(self.ep.current_page - 1)
  File "c:\python34\lib\site-packages\comiccrawler\core\__init__.py", line 208,
in init_images
    self.get_images()
  File "c:\python34\lib\site-packages\comiccrawler\core\__init__.py", line 340,
in get_images
    self.ep.current_url
  File "c:\python34\lib\site-packages\comiccrawler\mods\seemh.py", line 97, in g
et_images
    return ctx.call("getFiles", path, files, host)
  File "c:\python34\lib\site-packages\execjs\_abstract_runtime_context.py", line
 37, in call
    return self._call(name, *args)
  File "c:\python34\lib\site-packages\execjs\_external_runtime.py", line 87, in
_call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=ident
ifier, args=args))
  File "c:\python34\lib\site-packages\execjs\_external_runtime.py", line 73, in
_eval
    return self.exec_(code)
  File "c:\python34\lib\site-packages\execjs\_abstract_runtime_context.py", line
 18, in exec_
    return self._exec_(source)
  File "c:\python34\lib\site-packages\execjs\_external_runtime.py", line 83, in
_exec_
    return self._extract_result(output)
  File "c:\python34\lib\site-packages\execjs\_external_runtime.py", line 165, in
 _extract_result
    raise exceptions.ProgramError(value)
execjs._exceptions.ProgramError: TypeError: 对象不支持此属性或方法
```

**Comment by eight04** [comment]
有安裝 Node.js 嗎？
https://github.com/eight04/ComicCrawler#install-nodejs
