### ISSUE TITLE
漫畫堆下載錯誤 (node_vm2.VMError: atob is not defined)

### ISSUE THREAD

**Issue by IthildinX** [eight04/ComicCrawler#265]
先前手動將www.manhuabei.com加入模組後可繼續解析並下載，
但目前只能更新或解析新漫畫，但下載時無法解析圖片網址了

漫畫網址
https://www.manhuabei.com/manhua/shisedalu/

錯誤訊息
Start download 食色大陆
Start downloading 食色大陆
total 401 episode.
Downloading ep 396、幽来香
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\comiccrawler\crawler.py", line 336, in error_loop
    process()
  File "c:\python38\lib\site-packages\comiccrawler\crawler.py", line 287, in download
    crawler.init()
  File "c:\python38\lib\site-packages\comiccrawler\crawler.py", line 51, in init
    self.init_images(self.ep.current_page - 1)
  File "c:\python38\lib\site-packages\comiccrawler\crawler.py", line 58, in init_images
    self.get_images()
  File "c:\python38\lib\site-packages\comiccrawler\crawler.py", line 184, in get_images
    images = self.mod.get_images(
  File "c:\python38\lib\site-packages\comiccrawler\mods\manhuadui.py", line 58, in get_images
    images = eval("""
  File "c:\python38\lib\site-packages\node_vm2\__init__.py", line 28, in eval
    return vm.run(code)
  File "c:\python38\lib\site-packages\node_vm2\__init__.py", line 131, in run
    return self.communicate({"action": "run", "code": code})
  File "c:\python38\lib\site-packages\node_vm2\__init__.py", line 101, in communicate
    raise VMError(data["error"])
node_vm2.VMError: atob is not defined

**Comment by eight04** [comment]
我看 manhuabei.com 不在支援清單裡面。你是想詢問如何解決 `atob is not defined` 的問題嗎？

**Comment by IthildinX** [comment]
抱歉沒講完整

漫畫堆原網址www.manhuadui.com有支援，後續網址更新為www.manhuabei.com ( #259 有提及)
由於沒有更新，我自己修改manhuadui.py讓程式支援新網址
但目前多了解析問題沒辦法蠻力解決

**Comment by IthildinX** [comment]
如果修正這問題跟重寫差不多麻煩的話，可以考慮改成支援Oh漫畫嗎? (#257)
那邊連線比漫畫堆順一點，進度也快一點

**Comment by eight04** [comment]
`atob` 是瀏覽器中 decode base64 的函式。Node 裡面沒有，所以就會顯示 `atob is not defined`。若要在 Node 中模擬相同功能︰
https://github.com/eight04/ComicCrawler/blob/b05400c3ce003d5c4e3022b97fe1accfeb2272aa/comiccrawler/mods/manhuabei_m.py#L64-L66
