### ISSUE TITLE
Unexpected token error

### ISSUE THREAD

**Issue by bhpliu** [eight04/ComicCrawler#266]
Am I doing something wrong?  Thanks for any help
```

$ comiccrawler download https://www.manhuagui.com/comic/1639/
Start analyzing https://www.manhuagui.com/comic/1639/
Analyzing success!
Start downloading 哆啦A梦
total 88 episode.
Downloading ep 单行本 第01卷

/usr/local/lib/python3.5/site-packages/node_vm2/vm-server/index.js:10
rl.on("line", line => {
                    ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

^CTraceback (most recent call last):
  File "/usr/local/bin/comiccrawler", line 11, in <module>
    sys.exit(console_init())
  File "/usr/local/lib/python3.5/site-packages/comiccrawler/cli.py", line 61, in console_init
    console_download(arguments["<url>"], arguments["--dest"])
  File "/usr/local/lib/python3.5/site-packages/comiccrawler/cli.py", line 41, in console_download
    download(mission, savepath)
  File "/usr/local/lib/python3.5/site-packages/comiccrawler/crawler.py", line 226, in download
    crawl(mission, savepath)
  File "/usr/local/lib/python3.5/site-packages/comiccrawler/crawler.py", line 264, in crawl
    crawlpage(crawler)
  File "/usr/local/lib/python3.5/site-packages/comiccrawler/crawler.py", line 329, in crawlpage
    error_loop(download, download_error)
  File "/usr/local/lib/python3.5/site-packages/comiccrawler/crawler.py", line 336, in error_loop
    process()
  File "/usr/local/lib/python3.5/site-packages/comiccrawler/crawler.py", line 287, in download
    crawler.init()
  File "/usr/local/lib/python3.5/site-packages/comiccrawler/crawler.py", line 51, in init
    self.init_images(self.ep.current_page - 1)
  File "/usr/local/lib/python3.5/site-packages/comiccrawler/crawler.py", line 58, in init_images
    self.get_images()
  File "/usr/local/lib/python3.5/site-packages/comiccrawler/crawler.py", line 186, in get_images
    self.ep.current_url
  File "/usr/local/lib/python3.5/site-packages/comiccrawler/mods/seemh.py", line 108, in get_images
    with VM(js) as vm:
  File "/usr/local/lib/python3.5/site-packages/node_vm2/__init__.py", line 117, in __init__
    super().__init__(server)
  File "/usr/local/lib/python3.5/site-packages/node_vm2/__init__.py", line 55, in __init__
    server = default_bridge()
  File "/usr/local/lib/python3.5/site-packages/node_vm2/__init__.py", line 37, in default_bridge
    DEFAULT_BRIDGE = VMServer().start()
  File "/usr/local/lib/python3.5/site-packages/node_vm2/__init__.py", line 431, in start
    data = self.communicate({"action": "ping"})
  File "/usr/local/lib/python3.5/site-packages/node_vm2/__init__.py", line 492, in communicate
    event.wait()
  File "/usr/local/lib/python3.5/threading.py", line 549, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/local/lib/python3.5/threading.py", line 293, in wait
    waiter.acquire()
KeyboardInterrupt
```

**Comment by eight04** [comment]
It seems that your Node.js is outdated. Try upgrading Node.js to the latest version.

**Comment by bhpliu** [comment]
Thanks! it's working now
