### ISSUE TITLE
看漫畫無法下載

### ISSUE THREAD

**Issue by kesdoputr** [eight04/ComicCrawler#27]
http://tw.ikanman.com/comic/17739/
http://tw.ikanman.com/comic/4739/

試了兩本都沒辦法抓，node.js有灌了6.9.1

C:\Users\k7\Desktop>comiccrawler download http://tw.ikanman.com/comic/17739/
Start analyzing http://tw.ikanman.com/comic/17739/
Analyzing success!
Start downloading 智醬是女生！
total 51 episode.
Downloading ep 番外篇
Downloading 番外篇 page 1: http://i.hamreus.com:8080/ps4/z/zhijiangshinvsheng/番
外篇/01.JPG.webp

Traceback (most recent call last):
  File "c:\python34\lib\site-packages\comiccrawler\core\__init__.py", line 428,
in error_loop
    process()
  File "c:\python34\lib\site-packages\comiccrawler\core\__init__.py", line 404,
in download
    crawler.save_image()
  File "c:\python34\lib\site-packages\comiccrawler\core\__init__.py", line 282,
in save_image
    content_write(self.get_full_filename(), self.image_bin)
  File "c:\python34\lib\site-packages\comiccrawler\core\__init__.py", line 255,
in get_full_filename
    raise Exception("Can't determine file type.")
Exception: Can't determine file type.
Downloading 番外篇 page 1: http://idx0.hamreus.com:8080/ps4/z/zhijiangshinvsheng
/番外篇/01.JPG.webp

Traceback (most recent call last):
  File "c:\python34\lib\site-packages\comiccrawler\core\__init__.py", line 428,
in error_loop
    process()
  File "c:\python34\lib\site-packages\comiccrawler\core\__init__.py", line 404,
in download
    crawler.save_image()
  File "c:\python34\lib\site-packages\comiccrawler\core\__init__.py", line 282,
in save_image
    content_write(self.get_full_filename(), self.image_bin)
  File "c:\python34\lib\site-packages\comiccrawler\core\__init__.py", line 255,
in get_full_filename
    raise Exception("Can't determine file type.")
Exception: Can't determine file type.

**Comment by eight04** [comment]
https://docs.python.org.tw/3/library/imghdr.html
看來 python 3.5 才支援 .webp 檔。我等會修

如果急用的話可以把 python 更新到 3.5+ 版本

**Comment by eight04** [comment]
已於 2016.12.6 修正
