### ISSUE TITLE
突然無法開啟GUI了，第一次出現這種訊息。

### ISSUE THREAD

**Issue by HYL-Dave** [eight04/ComicCrawler#279]
(base) C:\WINDOWS\system32>comiccrawler gui
Failed to load session!
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\comiccrawler.exe\__main__.py", line 9, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\comiccrawler\cli.py", line 57, in console_init
    from .gui.main_window import MainWindow
  File "c:\programdata\anaconda3\lib\site-packages\comiccrawler\gui\main_window.py", line 23, in <module>
    from ..download_manager import download_manager
  File "c:\programdata\anaconda3\lib\site-packages\comiccrawler\download_manager.py", line 28, in <module>
    from .mission_manager import mission_manager
  File "c:\programdata\anaconda3\lib\site-packages\comiccrawler\mission_manager.py", line 196, in <module>
    mission_manager = MissionManager()
  File "c:\programdata\anaconda3\lib\site-packages\comiccrawler\mission_manager.py", line 30, in __init__
    self.load()
  File "c:\programdata\anaconda3\lib\site-packages\comiccrawler\mission_manager.py", line 68, in load
    self._load()
  File "c:\programdata\anaconda3\lib\site-packages\comiccrawler\mission_manager.py", line 78, in _load
    view = json_load(profile("view.json")) or []
  File "c:\programdata\anaconda3\lib\site-packages\comiccrawler\io.py", line 183, in json_load
    return json.load(fp)
  File "c:\programdata\anaconda3\lib\json\__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "c:\programdata\anaconda3\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "c:\programdata\anaconda3\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\programdata\anaconda3\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by eight04** [comment]
看起來讀取 view.json 時發生錯誤。你有修改過它嗎？

**Comment by HYL-Dave** [comment]
沒有修改過喔，因為這不是我的主力機，開發也都是在ubuntu或redhat上，所以沒機會去動這台的東西。

**Comment by HYL-Dave** [comment]
正確來說不是突然不行，在發生前這台電腦藍屏重開機後就發生了，只是我認為這造成檔案損壞的機會太低了

**Comment by HYL-Dave** [comment]
應該是當機的時間點太剛好，應該真的是當機的時間點很剛好吧，可能在修改寫入的時間點剛好當機了，我後來先移走讓開啟時自鄧重建view.json又開起來了。請問這個view.json主要的功能是什麼?暫存一些資料嗎?

**Comment by eight04** [comment]
`view.json` 存任務列表，`library.json` 存圖書館列表，`pool.json` 存任務的詳細資料。另外，可以在同個資料夾找找有沒有備份的檔案，名字類似 `view.json@yyyy-mm-dd`。
