### ISSUE TITLE
Problem ikanman.com

### ISSUE THREAD

**Issue by DENISBruno** [eight04/ComicCrawler#28]
http://www.ikanman.com/comic/3562/30918.html

Downloading 第01卷 page 1: 
http://i.hamreus.com:8080/ps2/W/WXZR/01/Wxzr01-001.jpg.webp

Traceback (most recent call last):
  File "c:\python35\lib\site-packages\comiccrawler\core\__init__.py", line 442, in error_loop
    process()
  File "c:\python35\lib\site-packages\comiccrawler\core\__init__.py", line 426, in download
    crawler.save_image()
  File "c:\python35\lib\site-packages\comiccrawler\core\__init__.py", line 312, in save_image
    content_write(self.get_full_filename(), self.image_bin)
  File "c:\python35\lib\site-packages\comiccrawler\core\__init__.py", line 288, in get_full_filename
    raise Exception("Bad file type: " + self.image_ext)
Exception: Bad file type: .webp

**Comment by eight04** [comment]
Please upgrade comiccrawler to latest version.
