### ISSUE TITLE
manhuagui下載失敗

### ISSUE THREAD

**Issue by Zivch** [eight04/ComicCrawler#284]
今天發生圖書館中許多manhuagui的漫畫都會無法下載。
範例網頁：
https://www.manhuagui.com/comic/27440/
https://www.manhuagui.com/comic/28004/

與之前ip被封鎖的情形不太相同，因為在瀏覽器可以開啟網頁。
系統訊息顯示如下：
Traceback (most recent call last):
  File "c:\users\zivthebear\appdata\local\programs\python\python37-32\lib\site-packages\comiccrawler\crawler.py", line 338, in error_loop
    process()
  File "c:\users\zivthebear\appdata\local\programs\python\python37-32\lib\site-packages\comiccrawler\crawler.py", line 289, in download
    crawler.init()
  File "c:\users\zivthebear\appdata\local\programs\python\python37-32\lib\site-packages\comiccrawler\crawler.py", line 51, in init
    self.init_images(self.ep.current_page - 1)
  File "c:\users\zivthebear\appdata\local\programs\python\python37-32\lib\site-packages\comiccrawler\crawler.py", line 58, in init_images
    self.get_images()
  File "c:\users\zivthebear\appdata\local\programs\python\python37-32\lib\site-packages\comiccrawler\crawler.py", line 188, in get_images
    self.ep.current_url
  File "c:\users\zivthebear\appdata\local\programs\python\python37-32\lib\site-packages\comiccrawler\mods\seemh.py", line 130, in get_images
    utils = re.search(r"SMH\.(utils=.+?),SMH\.imgData=", corejs).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

謝謝協助。

**Comment by eienmirimu** [comment]
我也是相同的問題

我有寄信給 @eight04 回報此問題

Traceback (most recent call last):
  File "c:\users\oo\appdata\local\programs\python\python38-32\lib\site-packages\comiccrawler\crawler.py", line 338, in error_loop
    process()
  File "c:\users\oo\appdata\local\programs\python\python38-32\lib\site-packages\comiccrawler\crawler.py", line 289, in download
    crawler.init()
  File "c:\users\oo\appdata\local\programs\python\python38-32\lib\site-packages\comiccrawler\crawler.py", line 51, in init
    self.init_images(self.ep.current_page - 1)
  File "c:\users\oo\appdata\local\programs\python\python38-32\lib\site-packages\comiccrawler\crawler.py", line 58, in init_images
    self.get_images()
  File "c:\users\oo\appdata\local\programs\python\python38-32\lib\site-packages\comiccrawler\crawler.py", line 186, in get_images
    images = self.mod.get_images(
  File "c:\users\oo\appdata\local\programs\python\python38-32\lib\site-packages\comiccrawler\mods\seemh.py", line 130, in get_images
    utils = re.search(r"SMH\.(utils=.+?),SMH\.imgData=", corejs).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

Something bad happened, skip the episode.


應該是 manhuagui 有改變網頁內容

所以程式才會出錯 (無法判斷)

**Comment by syaofox** [comment]
一样的问题，期待更新

Traceback (most recent call last):
  File "/home/syaofox/.local/lib/python3.8/site-packages/comiccrawler/crawler.py", line 338, in error_loop
    process()
  File "/home/syaofox/.local/lib/python3.8/site-packages/comiccrawler/crawler.py", line 289, in download
    crawler.init()
  File "/home/syaofox/.local/lib/python3.8/site-packages/comiccrawler/crawler.py", line 51, in init
    self.init_images(self.ep.current_page - 1)
  File "/home/syaofox/.local/lib/python3.8/site-packages/comiccrawler/crawler.py", line 58, in init_images
    self.get_images()
  File "/home/syaofox/.local/lib/python3.8/site-packages/comiccrawler/crawler.py", line 186, in get_images
    images = self.mod.get_images(
  File "/home/syaofox/.local/lib/python3.8/site-packages/comiccrawler/mods/seemh.py", line 130, in get_images
    utils = re.search(r"SMH\.(utils=.+?),SMH\.imgData=", corejs).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/syaofox/.local/lib/python3.8/site-packages/comiccrawler/crawler.py", line 338, in error_loop
    process()
  File "/home/syaofox/.local/lib/python3.8/site-packages/comiccrawler/crawler.py", line 289, in download
    crawler.init()
  File "/home/syaofox/.local/lib/python3.8/site-packages/comiccrawler/crawler.py", line 51, in init
    self.init_images(self.ep.current_page - 1)
  File "/home/syaofox/.local/lib/python3.8/site-packages/comiccrawler/crawler.py", line 58, in init_images
    self.get_images()
  File "/home/syaofox/.local/lib/python3.8/site-packages/comiccrawler/crawler.py", line 186, in get_images
    images = self.mod.get_images(
  File "/home/syaofox/.local/lib/python3.8/site-packages/comiccrawler/mods/seemh.py", line 130, in get_images
    utils = re.search(r"SMH\.(utils=.+?),SMH\.imgData=", corejs).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
Stop downloading
Session saved

**Comment by Zivch** [comment]
感謝大神！
