### ISSUE TITLE
腾讯动漫的漫画无法下载

### ISSUE THREAD

**Issue by yhxkry** [eight04/ComicCrawler#288]
之前都能用的，最近发现不管怎么改cookie都下载报错：

Traceback (most recent call last):
  File "c:\users\rickyyao\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\crawler.py", line 338, in error_loop
    process()
  File "c:\users\rickyyao\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\crawler.py", line 289, in download
    crawler.init()
  File "c:\users\rickyyao\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\crawler.py", line 51, in init
    self.init_images(self.ep.current_page - 1)
  File "c:\users\rickyyao\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\crawler.py", line 58, in init_images
    self.get_images()
  File "c:\users\rickyyao\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\crawler.py", line 188, in get_images
    self.ep.current_url
  File "c:\users\rickyyao\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\mods\qq.py", line 36, in get_images
    nonce = re.search("window\.nonce = (.+)", html).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

还试过下载免费的漫画，也是报这样的错，看来不是我输错cookie的问题。

请问是什么原因？还有别人也这样吗?

谢谢！

**Comment by IthildinX** [comment]
免費漫畫有一樣的錯誤訊息

https://ac.qq.com/Comic/comicInfo/id/647595

Start download 这个修士来自未来
Start downloading 这个修士来自未来
total 53 episode.
Downloading ep 45 - 这个修士来自未来：041 灵毒拔除
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\comiccrawler\crawler.py", line 338, in error_loop
    process()
  File "c:\python38\lib\site-packages\comiccrawler\crawler.py", line 289, in download
    crawler.init()
  File "c:\python38\lib\site-packages\comiccrawler\crawler.py", line 51, in init
    self.init_images(self.ep.current_page - 1)
  File "c:\python38\lib\site-packages\comiccrawler\crawler.py", line 58, in init_images
    self.get_images()
  File "c:\python38\lib\site-packages\comiccrawler\crawler.py", line 186, in get_images
    images = self.mod.get_images(
  File "c:\python38\lib\site-packages\comiccrawler\mods\qq.py", line 36, in get_images
    nonce = re.search("window\.nonce = (.+)", html).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
