### ISSUE TITLE
ohmanhua 下載失敗

### ISSUE THREAD

**Issue by eienmirimu** [eight04/ComicCrawler#295]
錯誤訊息如下

Traceback (most recent call last):
  File "c:\users\appdata\local\programs\python\python38\lib\site-packages\comiccrawler\crawler.py", line 338, in error_loop
    process()
  File "c:\users\appdata\local\programs\python\python38\lib\site-packages\comiccrawler\crawler.py", line 289, in download
    crawler.init()
  File "c:\users\appdata\local\programs\python\python38\lib\site-packages\comiccrawler\crawler.py", line 51, in init
    self.init_images(self.ep.current_page - 1)
  File "c:\users\appdata\local\programs\python\python38\lib\site-packages\comiccrawler\crawler.py", line 58, in init_images
    self.get_images()
  File "c:\users\appdata\local\programs\python\python38\lib\site-packages\comiccrawler\crawler.py", line 186, in get_images
    images = self.mod.get_images(
  File "c:\users\appdata\local\programs\python\python38\lib\site-packages\comiccrawler\mods\oh.py", line 114, in get_images
    imgs = eval(code)
  File "c:\users\appdata\local\programs\python\python38\lib\site-packages\node_vm2\__init__.py", line 28, in eval
    return vm.run(code)
  File "c:\users\appdata\local\programs\python\python38\lib\site-packages\node_vm2\__init__.py", line 131, in run
    return self.communicate({"action": "run", "code": code})
  File "c:\users\appdata\local\programs\python\python38\lib\site-packages\node_vm2\__init__.py", line 101, in communicate
    raise VMError(data["error"])
node_vm2.VMError: setInterval is not defined

希望 @eight04 有空閒的時候  可以更新一下腳本

謝謝您~

**Comment by eight04** [comment]
> https://www.cocomanhua.com/17051/
>
> 第49回~53回

**Comment by eienmirimu** [comment]
cocomanhua 跟 ohmanhua 都是同樣的網站

一樣都會有下載錯誤的問題

需要等 @eight04  更新腳本

辛苦你了~ 謝謝~

**Comment by eight04** [comment]
Move to #306
