### ISSUE TITLE
COCO漫畫 (原OH漫畫) 下載出錯

### ISSUE THREAD

**Issue by IthildinX** [eight04/ComicCrawler#301]
漫畫網址:  https://www.cocomanhua.com/11839/

錯誤訊息: 

Start download 战国千年
Start downloading 战国千年
total 148 episode.
Downloading ep 128 无愧于心
Traceback (most recent call last):
  File "C:\Users\Ithildin\AppData\Roaming\Python\Python39\site-packages\comiccrawler\crawler.py", line 338, in error_loop
    process()
  File "C:\Users\Ithildin\AppData\Roaming\Python\Python39\site-packages\comiccrawler\crawler.py", line 289, in download
    crawler.init()
  File "C:\Users\Ithildin\AppData\Roaming\Python\Python39\site-packages\comiccrawler\crawler.py", line 51, in init
    self.init_images(self.ep.current_page - 1)
  File "C:\Users\Ithildin\AppData\Roaming\Python\Python39\site-packages\comiccrawler\crawler.py", line 58, in init_images
    self.get_images()
  File "C:\Users\Ithildin\AppData\Roaming\Python\Python39\site-packages\comiccrawler\crawler.py", line 186, in get_images
    images = self.mod.get_images(
  File "C:\Users\Ithildin\AppData\Roaming\Python\Python39\site-packages\comiccrawler\mods\oh.py", line 114, in get_images
    imgs = eval(code)
  File "C:\Users\Ithildin\AppData\Roaming\Python\Python39\site-packages\node_vm2\__init__.py", line 28, in eval
    return vm.run(code)
  File "C:\Users\Ithildin\AppData\Roaming\Python\Python39\site-packages\node_vm2\__init__.py", line 131, in run
    return self.communicate({"action": "run", "code": code})
  File "C:\Users\Ithildin\AppData\Roaming\Python\Python39\site-packages\node_vm2\__init__.py", line 101, in communicate
    raise VMError(data["error"])
node_vm2.VMError: setInterval is not defined

**Comment by eight04** [comment]
Move to #306
