### ISSUE TITLE
Sankaku下载出错

### ISSUE THREAD

**Issue by tuper579** [eight04/ComicCrawler#305]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/comiccrawler/crawler.py", line 338, in error_loop
    process()
  File "/usr/local/lib/python3.6/dist-packages/comiccrawler/crawler.py", line 289, in download
    crawler.init()
  File "/usr/local/lib/python3.6/dist-packages/comiccrawler/crawler.py", line 51, in init
    self.init_images(self.ep.current_page - 1)
  File "/usr/local/lib/python3.6/dist-packages/comiccrawler/crawler.py", line 58, in init_images
    self.get_images()
  File "/usr/local/lib/python3.6/dist-packages/comiccrawler/crawler.py", line 188, in get_images
    self.ep.current_url
  File "/usr/local/lib/python3.6/dist-packages/comiccrawler/mods/sankaku.py", line 52, in get_images
    return ["https:" + unescape(u.group(1))]
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by tuper579** [comment]
Sankaku服务器问题，已恢复
