### ISSUE TITLE
Copymanga拷贝漫画解析错误

### ISSUE THREAD

**Issue by yhxkry** [eight04/ComicCrawler#316]
想加入拷贝漫画，复制漫画的链接之后解析错误

显示：

解析错误！'NoneType' object has no attribute 'group'

请问是什么原因？已经更新到最新的版本了，我看9月的更新日志里也有提到修复了拷贝漫画，但是实际上却还是有问题哎。

**Comment by yhxkry** [comment]
我解析deviantart的链接的时候也显示类似的错误：

Thread crashed: <function DownloadManager.start_analyze.<locals>.analyze_thread at 0x0000024A65BBEC80>
Traceback (most recent call last):
  File "c:\users\rickyyao\appdata\local\programs\python\python37\lib\site-packages\worker\__init__.py", line 474, in wrap_worker
    self.ret = self.worker(*args, **kwargs)
  File "c:\users\rickyyao\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\download_manager.py", line 163, in analyze_thread
    Analyzer(mission).analyze()
  File "c:\users\rickyyao\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\analyzer.py", line 57, in analyze
    self.do_analyze()
  File "c:\users\rickyyao\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\analyzer.py", line 86, in do_analyze
    self.analyze_pages()
  File "c:\users\rickyyao\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\analyzer.py", line 107, in analyze_pages
    eps = self.mission.module.get_episodes(self.html, url)
  File "c:\users\rickyyao\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\mods\deviantart.py", line 79, in get_episodes
    for id in gallery["items"]:
TypeError: 'NoneType' object is not subscriptable

能麻烦大佬看看原因吗？是9月15的最新版本。

**Comment by eight04** [comment]
#317 有修了，不過我自己測試時會遇到SSL錯誤，得在設定檔裡加上︰
```ini
[拷貝]
verify = false
```
