### ISSUE TITLE
How can i use it as module alongside asyncio.queue

### ISSUE THREAD

**Issue by xu3s** [eight04/ComicCrawler#331]
Hi, i have this issue where i get this exception
```
Traceback (most recent call last):                                        File "/data/data/com.termux/files/home/mandex/venv/lib/python3.10/site-packages/comiccrawler/crawler.py", line 340, in error_loop
    process()                                                             File "/data/data/com.termux/files/home/mandex/venv/lib/python3.10/site-packages/comiccrawler/crawler.py", line 289, in download
    crawler.init()
  File "/data/data/com.termux/files/home/mandex/venv/lib/python3.10/site-packages/comiccrawler/crawler.py", line 51, in init                        self.init_images(self.ep.current_page - 1)
  File "/data/data/com.termux/files/home/mandex/venv/lib/python3.10/site-packages/comiccrawler/crawler.py", line 57, in init_images                 self.get_html()                                                       File "/data/data/com.termux/files/home/mandex/venv/lib/python3.10/site-packages/comiccrawler/crawler.py", line 177, in get_html
    self.html = self.downloader.html(self.ep.current_url, referer=self.mission.url)                                                               File "/data/data/com.termux/files/home/mandex/venv/lib/python3.10/site-packages/comiccrawler/module_grabber.py", line 11, in html
    return self.grab(grabhtml, url, **kwargs)                             File "/data/data/com.termux/files/home/mandex/venv/lib/python3.10/site-packages/comiccrawler/module_grabber.py", line 30, in grab
    return grab_method(url, **new_kwargs)
  File "/data/data/com.termux/files/home/mandex/venv/lib/python3.10/site-packages/comiccrawler/grabber.py", line 159, in grabhtml                   r = grabber(*args, **kwargs)
  File "/data/data/com.termux/files/home/mandex/venv/lib/python3.10/site-packages/comiccrawler/grabber.py", line 112, in grabber                    r = await_(do_request, s, url, proxies, retry, **kwargs)              File "/data/data/com.termux/files/home/mandex/venv/lib/python3.10/site-packages/worker/__init__.py", line 905, in wrapped
    return f(*args, **kwargs)                                             File "/data/data/com.termux/files/home/mandex/venv/lib/python3.10/site-packages/worker/__init__.py", line 927, in await_
    return async_(callback, *args, **kwargs).get()
  File "/data/data/com.termux/files/home/mandex/venv/lib/python3.10/site-packages/worker/__init__.py", line 677, in get                             handle = current()
  File "/data/data/com.termux/files/home/mandex/venv/lib/python3.10/site-packages/worker/__init__.py", line 882, in current                         return WORKER_POOL.current()                                          File "/data/data/com.termux/files/home/mandex/venv/lib/python3.10/site-packages/worker/__init__.py", line 805, in current
    return self.pool[threading.current_thread()][-1]                    KeyError: <Thread(ThreadPoolExecutor-0_0, started 516055987440)>        wait 10 seconds...
```
When i try to make generator and run it in executor, it work fine when called directly (without `await loop.run_in_executor())

Here is my processor code that throw the error
```python
    async def process(self,ctx:commands.Context,chapter):
        loop = asyncio.get_running_loop()
        await ctx.reply(f'Processing to dowload episode(s) ***{",".join([str(a) for a in chapter])}*** Please wait!')
        def _process_download():
            for epl in self.manga.mdownload(chapter):
                queue.put_nowait((ctx,epl))

        await loop.run_in_executor(None,_process_download)
```
 And here is the `mdownload() ` wrapper for the download method for this
```python
    def mdownload(self, to_dl:list):

        cf = uptobox.check_files(os.path.join('/raws',self.mission.title))
        if cf['status'] == 'ok':
            dbx_files = cf['entries']
        else:
            print(f'error \n{cf["info"]}')
            dbx_files = cf['entries']

        init_state = self.mission.state
        for ep in self.mission.episodes:
            ep.skip = True
        for n, ep in enumerate(self.mission.episodes, 0):
            print(n)
            if n in to_dl and f'{ep.title}.zip' not in dbx_files:
                ep.skip = False
                with tempfile.TemporaryDirectory() as tempdir:
                    print(f'tempdir: {tempdir}')
                    print(f'mission: \n{self.mission}')
                    try:
                        download(self.mission, tempdir)
                        print(f'....listdir: {os.listdir(tempdir)}')
                    except Exception as e:
                        print(f'...listdir: {os.listdir(tempdir)}')
                        print(f'download exveption: {e}\n\n')
                        break
                    print(os.path.join(tempdir,self.mission.title))
                    shutil.make_archive(os.path.join(tempdir,ep.title),
                            'zip',
                            os.path.join(tempdir,self.mission.title))

                    uped = uptobox.upload(
                            os.path.join(tempdir,
                            f'{ep.title}.zip'),
                            box_path=os.path.join(
                                '/raws', self.mission.title))
                    if uped['status'] == 'ok':
                        message = f'File Name: {uped["name"]}\nDl_url: {uped["url"]}'
                    else:
                        message = uped
                    yield message
                ep.skip = True
                self.mission.state = init_state
```
Do you have suggestions how to fix this? I just want this process to not block my bot to receive another command,
Thanks in advance.

**Comment by eight04** [comment]
I think the problem is that threads initialized by asyncio are not registered in pyThreadWorker's worker pool:
https://github.com/eight04/pyWorker/blob/cae866af612e0c818e08f9a2e27f9cfd5f87ec14/worker/__init__.py#L805
We can't create it automatically because we don't know when to cleanup.

Try wrapping `download` in a parent-less worker:
```py
from worker import create_worker

def safe_download(...);
  err = None
  def target():
    try:
      download(...)
    except Exception as new_err:
      nonlocal err
      err = new_err
  w = create_worker(target, parent=False)
  w.start()
  w.join()
  if err:
    raise err

# replace download with safe_download
safe_download(self.mission, tempdir)
```

**Comment by eight04** [comment]
https://github.com/eight04/pyWorker/issues/5

**Comment by xu3s** [comment]
Your code work, thank you so much,
I was stuck on this part for about 3 days.
Once again thank you
