### ISSUE TITLE
dmzj改版了，现在无法下载了...需要修正。

### ISSUE THREAD

**Issue by yukiflandre** [eight04/ComicCrawler#343]
目前dmzj需要登陆后才能获得漫画内容了，希望作者可以修复，感谢。

**Comment by eight04** [comment]
連結？

**Comment by yukiflandre** [comment]
> 連結？

https://manhua.dmzj.com

根據另外一款脚本comicread的反饋來看，5級用戶可以獲取版權漫畫外的所有隱藏漫畫，指定api+用戶uid即可獲取章節列表，無需登錄和cookie。
不過我沒有抓包，不清楚具體的api。

報錯信息：
Start analyzing https://manhua.dmzj.com/zhuanshengqiwangzidemofaquanjie/
Thread crashed: <function DownloadManager.start_analyze.<locals>.analyze_thread at 0x000001FAB7F29790>
Traceback (most recent call last):
  File "C:\Users\baby\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\worker\__init__.py", line 474, in wrap_worker
    self.ret = self.worker(*args, **kwargs)
  File "C:\Users\baby\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\comiccrawler\download_manager.py", line 171, in analyze_thread
    Analyzer(mission).analyze()
  File "C:\Users\baby\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\comiccrawler\analyzer.py", line 57, in analyze
    self.do_analyze()
  File "C:\Users\baby\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\comiccrawler\analyzer.py", line 83, in do_analyze
    self.mission.title = self.mission.module.get_title(
  File "C:\Users\baby\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\comiccrawler\mods\dmzj.py", line 19, in get_title
    return re.search("<h1>(.+?)</h1>", html).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by eight04** [comment]
剛測試了一下，連不上dmzj

**Comment by eight04** [comment]
Hmm 我沒有dmzj的帳號，點進連結直接被轉回首頁

**Comment by yukiflandre** [comment]
> Hmm 我沒有dmzj的帳號，點進連結直接被轉回首頁

你可以使用下面的腳本避免登陸帳號
https://github.com/hymbz/ComicReadScript
