### ISSUE TITLE
愛看漫下載失效

### ISSUE THREAD

**Issue by icandura** [eight04/ComicCrawler#35]
http://tw.ikanman.com/comic/6767/ 無法下載愛看漫的漫畫。
試了不同網路上的2臺電腦，node.js分別有灌0.12.9和6.10.0，python分別為3.5.1和3.6.0
一直重複下列訊息的`Traceback`至`AttributeError`部分：

> 
comiccrawler download http://tw.ikanman.com/comic/6767/
Start analyzing http://tw.ikanman.com/comic/6767/
Analyzing success!
Start downloading 赤河戀影
total 28 episode.
Downloading ep 第01卷
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\comiccrawler\core\__init__.py", line 555, in error_loop
    process()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\comiccrawler\core\__init__.py", line 505, in download
    crawler.init()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\comiccrawler\core\__init__.py", line 347, in init
    self.init_images(self.ep.current_page - 1)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\comiccrawler\core\__init__.py", line 354, in init_images
    self.get_images()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\comiccrawler\core\__init__.py", line 472, in get_images
    self.ep.current_url
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\comiccrawler\mods\seemh.py", line 63, in get_images
    crypto = re.search(r"(var CryptoJS.+?)var pVars", configjs, re.S).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\comiccrawler\core\__init__.py", line 555, in error_loop
    process()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\comiccrawler\core\__init__.py", line 505, in download
    crawler.init()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\comiccrawler\core\__init__.py", line 347, in init
    self.init_images(self.ep.current_page - 1)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\comiccrawler\core\__init__.py", line 354, in init_images
    self.get_images()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\comiccrawler\core\__init__.py", line 472, in get_images
    self.ep.current_url
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\comiccrawler\mods\seemh.py", line 63, in get_images
    crypto = re.search(r"(var CryptoJS.+?)var pVars", configjs, re.S).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by eight04** [comment]
已於 2017.3.6 修正

**Comment by icandura** [comment]
謝謝~可以下載了~
