### ISSUE TITLE
檢查更新時comicbus出現錯誤

### ISSUE THREAD

**Issue by kesdoputr** [eight04/ComicCrawler#351]
你好，已使用pip install comiccrawler --upgrade --upgrade-strategy eager
update到最新，使用時會出現以下錯誤訊息，無限的站都會出現錯誤
![k7shot_001](https://github.com/eight04/ComicCrawler/assets/16981364/4c0375ec-f7ab-44d4-9e79-29824032ab10)
![k7shot_002](https://github.com/eight04/ComicCrawler/assets/16981364/89c2023b-61c7-4504-8cf8-800f7365cb86)

```
Start analyzing https://comicbus.com/html/14884.html
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\lib\site-packages\deno_vm\__init__.py", line 244, in start
    self.process = Popen(args, bufsize=0, stdin=PIPE, stdout=PIPE) # pylint: disable=consider-using-with
  File "C:\Users\User\AppData\Local\Programs\Python\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\User\AppData\Local\Programs\Python\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系統找不到指定的檔案。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\lib\site-packages\comiccrawler\batch_analyzer.py", line 59, in do_analyze
    Analyzer(mission).analyze()
  File "C:\Users\User\AppData\Local\Programs\Python\lib\site-packages\comiccrawler\analyzer.py", line 57, in analyze
    self.do_analyze()
  File "C:\Users\User\AppData\Local\Programs\Python\lib\site-packages\comiccrawler\analyzer.py", line 86, in do_analyze
    self.analyze_pages()
  File "C:\Users\User\AppData\Local\Programs\Python\lib\site-packages\comiccrawler\analyzer.py", line 107, in analyze_pages
    eps = list(self.mission.module.get_episodes(self.html, url))
  File "C:\Users\User\AppData\Local\Programs\Python\lib\site-packages\comiccrawler\mods\eight.py", line 50, in get_episodes
    with VM(js) as vm:
  File "C:\Users\User\AppData\Local\Programs\Python\lib\site-packages\deno_vm\__init__.py", line 122, in __init__
    super().__init__(server=server, console=console)
  File "C:\Users\User\AppData\Local\Programs\Python\lib\site-packages\deno_vm\__init__.py", line 55, in __init__
    server = default_bridge()
  File "C:\Users\User\AppData\Local\Programs\Python\lib\site-packages\deno_vm\__init__.py", line 37, in default_bridge
    DEFAULT_BRIDGE = VMServer().start()
  File "C:\Users\User\AppData\Local\Programs\Python\lib\site-packages\deno_vm\__init__.py", line 246, in start
    raise VMError(f"Failed starting VM server. '{self.command}' is unavailable.") from err
deno_vm.VMError: Failed starting VM server. 'deno' is unavailable.
Start analyzing https://comicbus.com/html/8956.html
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\lib\site-packages\deno_vm\__init__.py", line 244, in start
    self.process = Popen(args, bufsize=0, stdin=PIPE, stdout=PIPE) # pylint: disable=consider-using-with
  File "C:\Users\User\AppData\Local\Programs\Python\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\User\AppData\Local\Programs\Python\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系統找不到指定的檔案。
```

**Comment by eight04** [comment]
現在comiccrawler需要安裝deno
詳見安裝說明

**Comment by kesdoputr** [comment]
感謝回答，裝了deno之後問題解決了，謝謝m(_ _)m
