### ISSUE TITLE
Python 3.12 Error

### ISSUE THREAD

**Issue by x2443120** [eight04/ComicCrawler#352]
```
Failed to load session!
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Scripts\comiccrawler.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\cli.py", line 57, in console_init
    from .gui.main_window import MainWindow
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\gui\main_window.py", line 23, in <module>
    from ..download_manager import download_manager
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\download_manager.py", line 28, in <module>
    from .mission_manager import mission_manager
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\mission_manager.py", line 196, in <module>
    mission_manager = MissionManager()
                      ^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\mission_manager.py", line 30, in __init__
    self.load()
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\mission_manager.py", line 68, in load
    self._load()
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\mission_manager.py", line 109, in _load
    mission = create_mission(**m_data)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\mission.py", line 43, in create_mission
    return MissionProxy(Mission(*args, **kwargs))
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\mission.py", line 18, in __init__
    self.module = get_module(url)
                  ^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\mods\__init__.py", line 106, in get_module
    self.load()
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\mods\__init__.py", line 63, in load
    self.mods.add(import_module("comiccrawler.mods." + name))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\mods\seemh.py", line 13, in <module>
    from lzstring import LZString
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\lzstring\__init__.py", line 11, in <module>
    from future import standard_library
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\future\standard_library\__init__.py", line 65, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
```

**Comment by eight04** [comment]
https://github.com/gkovacs/lz-string-python/pull/6
LZString在python 3.12有bug還沒修。

還是說我們改用javascript的lzstring?

**Comment by eight04** [comment]
https://github.com/PythonCharmers/python-future/issues/625

**Comment by x2443120** [comment]
感謝提供資訊，降版本之後的確是正常了
