### ISSUE TITLE
下载腾讯动漫的漫画报错

### ISSUE THREAD

**Issue by yhxkry** [eight04/ComicCrawler#354]
例子是下载《黄雀传》
链接地址：https://ac.qq.com/Comic/comicInfo/id/553285
前面的章节是免费的，但是下载也会报错，报错内容如下：

Start download 黄雀传
Start downloading 黄雀传
total 193 episode.
Downloading ep 1 - 黄雀传：第1话
Traceback (most recent call last):
  File "C:\Users\yaoli\AppData\Local\Programs\Python\Python310\lib\site-packages\deno_vm\__init__.py", line 244, in start
    self.process = Popen(args, bufsize=0, stdin=PIPE, stdout=PIPE) # pylint: disable=consider-using-with
  File "C:\Users\yaoli\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\yaoli\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\yaoli\AppData\Local\Programs\Python\Python310\lib\site-packages\comiccrawler\crawler.py", line 345, in error_loop
    process()
  File "C:\Users\yaoli\AppData\Local\Programs\Python\Python310\lib\site-packages\comiccrawler\crawler.py", line 294, in download
    crawler.init()
  File "C:\Users\yaoli\AppData\Local\Programs\Python\Python310\lib\site-packages\comiccrawler\crawler.py", line 53, in init
    self.init_images(self.ep.current_page - 1)
  File "C:\Users\yaoli\AppData\Local\Programs\Python\Python310\lib\site-packages\comiccrawler\crawler.py", line 60, in init_images
    self.get_images()
  File "C:\Users\yaoli\AppData\Local\Programs\Python\Python310\lib\site-packages\comiccrawler\crawler.py", line 191, in get_images
    images = self.mod.get_images(
  File "C:\Users\yaoli\AppData\Local\Programs\Python\Python310\lib\site-packages\comiccrawler\mods\qq.py", line 63, in get_images
    data = eval(code)
  File "C:\Users\yaoli\AppData\Local\Programs\Python\Python310\lib\site-packages\deno_vm\__init__.py", line 25, in eval
    with VM(**options) as vm:
  File "C:\Users\yaoli\AppData\Local\Programs\Python\Python310\lib\site-packages\deno_vm\__init__.py", line 122, in __init__
    super().__init__(server=server, console=console)
  File "C:\Users\yaoli\AppData\Local\Programs\Python\Python310\lib\site-packages\deno_vm\__init__.py", line 55, in __init__
    server = default_bridge()
  File "C:\Users\yaoli\AppData\Local\Programs\Python\Python310\lib\site-packages\deno_vm\__init__.py", line 37, in default_bridge
    DEFAULT_BRIDGE = VMServer().start()
  File "C:\Users\yaoli\AppData\Local\Programs\Python\Python310\lib\site-packages\deno_vm\__init__.py", line 246, in start
    raise VMError(f"Failed starting VM server. '{self.command}' is unavailable.") from err
deno_vm.VMError: Failed starting VM server. 'deno' is unavailable.
wait 10 seconds...
Stop downloading
停止下載
Session saved

**Comment by eight04** [comment]
2023.10.11後ComicCrawler改用deno執行JavaScript。
可以參考︰https://github.com/eight04/ComicCrawler#install-deno

**Comment by yhxkry** [comment]
> 2023.10.11後ComicCrawler改用deno執行JavaScript。 可以參考︰https://github.com/eight04/ComicCrawler#install-deno

谢谢，可以了，没留意增加了deno...
我一开始安装之后直接使用comiccrawler，还是报同样的错误。然后重启电脑才可以了
