### ISSUE TITLE
manhuagui下載錯誤

### ISSUE THREAD

**Issue by rickchen16** [eight04/ComicCrawler#357]
var servs的宣告換地方了
本來在core_BBC13C98D801D055637C3CB80B5C16EA8607DB00.js
改到ps_EEAA58B2CE247D2B51B7F246017F75C68469385F.js
url: https://cf.mhgui.com/scripts/ps_EEAA58B2CE247D2B51B7F246017F75C68469385F.js

錯誤訊息
Traceback (most recent call last):
  File "C:\Users\LIMIT\AppData\Local\Programs\Python\Python311\Lib\site-packages\comiccrawler\crawler.py", line 345, in error_loop
    process()
  File "C:\Users\LIMIT\AppData\Local\Programs\Python\Python311\Lib\site-packages\comiccrawler\crawler.py", line 294, in download
    crawler.init()
  File "C:\Users\LIMIT\AppData\Local\Programs\Python\Python311\Lib\site-packages\comiccrawler\crawler.py", line 53, in init
    self.init_images(self.ep.current_page - 1)
  File "C:\Users\LIMIT\AppData\Local\Programs\Python\Python311\Lib\site-packages\comiccrawler\crawler.py", line 60, in init_images
    self.get_images()
  File "C:\Users\LIMIT\AppData\Local\Programs\Python\Python311\Lib\site-packages\comiccrawler\crawler.py", line 191, in get_images
    images = self.mod.get_images(
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LIMIT\AppData\Local\Programs\Python\Python311\Lib\site-packages\comiccrawler\mods\seemh.py", line 113, in get_images
    servs = re.search(r"var servs=(.+?),pfuncs=", corejs).group(1)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

ps_EEAA58B2CE247D2B51B7F246017F75C68469385F.js內容
var servs = [{
    name: "自动",
    hosts: [{
        h: "i",
        w: .1
    }, {
        h: "eu",
        w: 3
    }, {
        h: "eu1",
        w: 3
    }, {
        h: "us",
        w: 1
    }, {
        h: "us1",
        w: 1
    }, {
        h: "us2",
        w: 1
    }, {
        h: "us3",
        w: 1
    }]
}, {
    name: "电信",
    hosts: [{
        h: "eu",
        w: 1
    }, {
        h: "eu1",
        w: 1
    }]
}, {
    name: "联通",
    hosts: [{
        h: "us",
        w: 1
    }, {
        h: "us1",
        w: 1
    }, {
        h: "us2",
        w: 1
    }, {
        h: "us3",
        w: 1
    }]
}];

**Comment by Zivch** [comment]
同樣的狀況，
在圖書館內可以更新進度，但無法下載。
希望eight04大大有空能幫忙修正。
範例連結：
https://www.manhuagui.com/comic/34441/

訊息：
Start download 终之退魔师
Start downloading 终之退魔师
total 188 episode.
Downloading ep 单话 第168话
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\comiccrawler\crawler.py", line 340, in error_loop
    process()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\comiccrawler\crawler.py", line 289, in download
    crawler.init()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\comiccrawler\crawler.py", line 51, in init
    self.init_images(self.ep.current_page - 1)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\comiccrawler\crawler.py", line 58, in init_images
    self.get_images()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\comiccrawler\crawler.py", line 186, in get_images
    images = self.mod.get_images(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\comiccrawler\mods\seemh.py", line 113, in get_images
    servs = re.search(r"var servs=(.+?),pfuncs=", corejs).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
wait 10 seconds...
