### ISSUE TITLE
manhuagui下載錯誤

### ISSUE THREAD

**Issue by rickchen16** [eight04/ComicCrawler#359]
https://tw.manhuagui.com/
又改js了
servs宣告沒了

錯誤訊息
Traceback (most recent call last):
  File "C:\Users\LIMIT\AppData\Local\Programs\Python\Python311\Lib\site-packages\comiccrawler\crawler.py", line 345, in error_loop
    process()
  File "C:\Users\LIMIT\AppData\Local\Programs\Python\Python311\Lib\site-packages\comiccrawler\crawler.py", line 294, in download
    crawler.init()
  File "C:\Users\LIMIT\AppData\Local\Programs\Python\Python311\Lib\site-packages\comiccrawler\crawler.py", line 53, in init
    self.init_images(self.ep.current_page - 1)
  File "C:\Users\LIMIT\AppData\Local\Programs\Python\Python311\Lib\site-packages\comiccrawler\crawler.py", line 60, in init_images
    self.get_images()
  File "C:\Users\LIMIT\AppData\Local\Programs\Python\Python311\Lib\site-packages\comiccrawler\crawler.py", line 191, in get_images
    images = self.mod.get_images(
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LIMIT\AppData\Local\Programs\Python\Python311\Lib\site-packages\comiccrawler\mods\seemh.py", line 110, in get_images
    servs = re.search(r"var servs=([^;]+)", configjs).group(1)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

https://cf.mhgui.com/scripts_tw/config_C14192D9179C13E3862E7748FA9A4C1A7397E0D1.js:formatted
var servs沒了
改宣告為var t
如以下js
    var t = [{
        name: "自動",
        hosts: [{
            h: "i",
            w: .1
        }, {
            h: "eu",
            w: 5
        }, {
            h: "eu1",
            w: 5
        }, {
            h: "us",
            w: 1
        }, {
            h: "us1",
            w: 1
        }, {
            h: "us2",
            w: 1
        }, {
            h: "us3",
            w: 1
        }]
    }, {
        name: "電信",
        hosts: [{
            h: "eu",
            w: 1
        }, {
            h: "eu1",
            w: 1
        }]
    }, {
        name: "聯通",
        hosts: [{
            h: "us",
            w: 1
        }, {
            h: "us1",
            w: 1
        }, {
            h: "us2",
            w: 1
        }, {
            h: "us3",
            w: 1
        }]
    }]
      , n = []
      , i = []
      , r = 0;

**Comment by Zivch** [comment]
一樣的問題。請大大有空再幫忙處理。
範例網頁：
https://www.manhuagui.com/comic/22260/

錯誤訊息：
Start download 配角X3
Start downloading 配角X3
total 20 episode.
Downloading ep 单话 第75话
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\comiccrawler\crawler.py", line 340, in error_loop
    process()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\comiccrawler\crawler.py", line 289, in download
    crawler.init()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\comiccrawler\crawler.py", line 51, in init
    self.init_images(self.ep.current_page - 1)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\comiccrawler\crawler.py", line 58, in init_images
    self.get_images()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\comiccrawler\crawler.py", line 186, in get_images
    images = self.mod.get_images(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\comiccrawler\mods\seemh.py", line 113, in get_images
    servs = re.search(r"var servs=(.+?),pfuncs=", corejs).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
wait 10 seconds...
