### ISSUE TITLE
下载哔哩哔哩漫画报错

### ISSUE THREAD

**Issue by yhxkry** [eight04/ComicCrawler#361]
下载哔哩哔哩漫画报错。
随便一个漫画都是会报错，例子是下载《我不受欢迎，怎么想都是你们的错》
链接地址：https://manga.bilibili.com/detail/mc27348?from=manga_person
即使下载免费的章节也会报错，报错内容如下：

Start download 我不受欢迎，怎么想都是你们的错
Start downloading 我不受欢迎，怎么想都是你们的错
total 264 episode.
Downloading ep 丧1 - 不受欢迎，所以要改变一下形象
Traceback (most recent call last):
  File "C:\Users\yaoli\AppData\Local\Programs\Python\Python310\lib\site-packages\comiccrawler\crawler.py", line 345, in error_loop
    process()
  File "C:\Users\yaoli\AppData\Local\Programs\Python\Python310\lib\site-packages\comiccrawler\crawler.py", line 294, in download
    crawler.init()
  File "C:\Users\yaoli\AppData\Local\Programs\Python\Python310\lib\site-packages\comiccrawler\crawler.py", line 53, in init
    self.init_images(self.ep.current_page - 1)
  File "C:\Users\yaoli\AppData\Local\Programs\Python\Python310\lib\site-packages\comiccrawler\crawler.py", line 60, in init_images
    self.get_images()
  File "C:\Users\yaoli\AppData\Local\Programs\Python\Python310\lib\site-packages\comiccrawler\crawler.py", line 191, in get_images
    images = self.mod.get_images(
  File "C:\Users\yaoli\AppData\Local\Programs\Python\Python310\lib\site-packages\comiccrawler\mods\bilibili_manga.py", line 118, in get_images
    image_index_file = decoder.decode(id, ep_id, image_index_file)
  File "C:\Users\yaoli\AppData\Local\Programs\Python\Python310\lib\site-packages\comiccrawler\mods\bilibili_manga.py", line 86, in decode
    return bytes(self.module.call('exportDecode', id, ep_id, list(data)))
  File "C:\Users\yaoli\AppData\Local\Programs\Python\Python310\lib\site-packages\deno_vm\__init__.py", line 162, in call
    return self.communicate({
  File "C:\Users\yaoli\AppData\Local\Programs\Python\Python310\lib\site-packages\deno_vm\__init__.py", line 105, in communicate
    raise VMError(data["error"])
deno_vm.VMError: (vm-server) failed getting VM, id=null
wait 10 seconds...

看起来是deno的报错？但是下载腾讯的漫画是正常的

**Comment by eight04** [comment]
是不是有IP鎖，連章節列表都看不到
![image](https://github.com/eight04/ComicCrawler/assets/1324510/14d13d91-7c06-4ccd-aa3c-3e928dbe9792)

**Comment by yhxkry** [comment]
这个我不知道唉，那随便换个你能打开的漫画可以下载吗？

**Comment by eight04** [comment]
Fixed in 2023.12.24
