### ISSUE TITLE
macOS執行錯誤

### ISSUE THREAD

**Issue by eggnog5566** [eight04/ComicCrawler#365]
謝謝 eight0 長期維護

長話短說
系統是 macOS Ventura 13.4 用 zsh 執行 comiccrawler gui
無法下 manhuagui 去更新 comiccrawler + deno(1.39.1)
之後跳出跟以往不同錯誤要回報
原本要導出文件
`comiccrawler gui >> ~/Desktop/debug1.log`
誤打誤撞居然解除 bug 了，正常下載

**以下是原錯誤提示**

`comiccrawler gui`
No schemas installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/comiccrawler/gui/core.py", line 57, in get_scale
    return float(p.stdout.read().rpartition(" ")[-1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: ''
Start analyzing https://www.manhuagui.com/comic/24332/
Analyzing success!
Start download 药屋少女的呢喃
Start downloading 药屋少女的呢喃
total 93 episode.
Downloading ep 番外篇 03卷附录
Downloading 番外篇 03卷附录 page 1: https://i.hamreus.com/ps3/y/ywsndnn_rxx/03卷附录/P0189-190.jpg.webp?e=1704721570&m=IRxCV6DdzK9eZvnFhZ8yNg

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/comiccrawler/crawler.py", line 345, in error_loop
    process()
  File "/usr/local/lib/python3.11/site-packages/comiccrawler/crawler.py", line 316, in download
    crawler.download_image()
  File "/usr/local/lib/python3.11/site-packages/comiccrawler/crawler.py", line 82, in download_image
    result = self.downloader.img(
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/comiccrawler/module_grabber.py", line 14, in img
    return self.grab(grabimg, url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/comiccrawler/module_grabber.py", line 30, in grab
    return grab_method(url, **new_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/comiccrawler/grabber.py", line 233, in grabimg
    with pb_manager.counter(total=total, unit="b", leave=False) as counter:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/enlighten/_basemanager.py", line 154, in counter
    return self._add_counter(self.counter_class, position=position, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/enlighten/_basemanager.py", line 285, in _add_counter
    self._set_scroll_area()
  File "/usr/local/lib/python3.11/site-packages/enlighten/_manager.py", line 185, in _set_scroll_area
    signal.signal(signal.SIGWINCH, self._stage_resize)
  File "/usr/local/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/signal.py", line 56, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: signal only works in main thread of the main interpreter
wait 10 seconds...
Stop downloading
停止下載

**Comment by eight04** [comment]
看起來有點像這個︰
https://github.com/Rockhopper-Technologies/enlighten/issues/59

**Comment by eight04** [comment]
試試編輯 `/usr/local/lib/python3.11/site-packages/comiccrawler/grabber.py`，修改第30行︰
```diff
diff --git a/comiccrawler/grabber.py b/comiccrawler/grabber.py
index 15ffb4d..12ab633 100644
--- a/comiccrawler/grabber.py
+++ b/comiccrawler/grabber.py
@@ -27,7 +27,7 @@ default_header = {
 cooldown = {}
 grabber_pool = {}
 grabber_pool_lock = Lock()
-pb_manager = enlighten.get_manager()
+pb_manager = enlighten.get_manager(no_resize=True)
 
 @contextmanager
 def get_request_lock(url):

```

**Comment by eggnog5566** [comment]
> 試試編輯 `/usr/local/lib/python3.11/site-packages/comiccrawler/grabber.py`，修改第30行︰
> 
> ```diff
> diff --git a/comiccrawler/grabber.py b/comiccrawler/grabber.py
> index 15ffb4d..12ab633 100644
> --- a/comiccrawler/grabber.py
> +++ b/comiccrawler/grabber.py
> @@ -27,7 +27,7 @@ default_header = {
>  cooldown = {}
>  grabber_pool = {}
>  grabber_pool_lock = Lock()
> -pb_manager = enlighten.get_manager()
> +pb_manager = enlighten.get_manager(no_resize=True)
>  
>  @contextmanager
>  def get_request_lock(url):
> ```

修改第 30 行成功執行沒報錯
剩下 gui 無法右鍵我就放棄
不影響使用就好
謝謝 eight 大
