### ISSUE TITLE
看漫畫下載失敗

### ISSUE THREAD

**Issue by seiya2000000** [eight04/ComicCrawler#366]
下載這個漫畫（https://www.manhuagui.com/comic/35634/ ）時出現以下的錯誤，
```
Traceback (most recent call last):
  File "C:\Users\kazamiw\AppData\Local\Programs\Python\Python312\Lib\site-packages\deno_vm\__init__.py", line 244, in start
    self.process = Popen(args, bufsize=0, stdin=PIPE, stdout=PIPE) # pylint: disable=consider-using-with
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kazamiw\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kazamiw\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 87] 參數錯誤。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\kazamiw\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\crawler.py", line 345, in error_loop
    process()
  File "C:\Users\kazamiw\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\crawler.py", line 294, in download
    crawler.init()
  File "C:\Users\kazamiw\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\crawler.py", line 53, in init
    self.init_images(self.ep.current_page - 1)
  File "C:\Users\kazamiw\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\crawler.py", line 60, in init_images
    self.get_images()
  File "C:\Users\kazamiw\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\crawler.py", line 191, in get_images
    images = self.mod.get_images(
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kazamiw\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\mods\seemh.py", line 118, in get_images
    with VM(js) as vm:
         ^^^^^^
  File "C:\Users\kazamiw\AppData\Local\Programs\Python\Python312\Lib\site-packages\deno_vm\__init__.py", line 122, in __init__
    super().__init__(server=server, console=console)
  File "C:\Users\kazamiw\AppData\Local\Programs\Python\Python312\Lib\site-packages\deno_vm\__init__.py", line 55, in __init__
    server = default_bridge()
             ^^^^^^^^^^^^^^^^
  File "C:\Users\kazamiw\AppData\Local\Programs\Python\Python312\Lib\site-packages\deno_vm\__init__.py", line 37, in default_bridge
    DEFAULT_BRIDGE = VMServer().start()
                     ^^^^^^^^^^^^^^^^^^
  File "C:\Users\kazamiw\AppData\Local\Programs\Python\Python312\Lib\site-packages\deno_vm\__init__.py", line 248, in start
    raise VMError("Failed starting VM server") from err
deno_vm.VMError: Failed starting VM server
wait 10 seconds...
```

**Comment by eight04** [comment]
你有安裝 deno 嗎？
https://github.com/eight04/ComicCrawler#install-deno

**Comment by seiya2000000** [comment]
我是用這個指令安裝deno的
irm https://deno.land/install.ps1 | iex

執行 deno upgrade 時顯示是最新畈 

C:\Users\kazamiw>deno upgrade
Looking up latest version
Local deno version 1.39.1 is the most recent release

**Comment by eight04** [comment]
試著編輯 `C:\Users\kazamiw\AppData\Local\Programs\Python\Python312\Lib\subprocess.py` 並在 1538 行
https://github.com/python/cpython/blob/8435fbfe4e1adb77ef6652bdcbd473b473a08ba3/Lib/subprocess.py#L1538
前加上一行︰
```py
                print(executable, args)
```
（注意空格數要和 `CreateProcess` 那行相同）
這樣報錯前，應該會印出用來啟動 deno 的指令，貼上來看看。
另外也貼一下 Python 版本 `python -V` 和 Windows 版本

----

網路上找了一下，大致提到幾個可能性

1. 防毒軟體問題
2. 參數過長
3. 環境變數過長

但是我沒看到確切的解決方式/原因，大多是重開機/重新安裝 python

**Comment by seiya2000000** [comment]
剛剛發現是deno要執行時被防毒軟體阻擋了，把它加入白名單內就正常了，
謝謝
