### ISSUE TITLE
Manhuagui檢查更新失敗

### ISSUE THREAD

**Issue by Zivch** [eight04/ComicCrawler#369]
eight04大大麻煩你了。
在圖書館中大部份manhuagui的漫畫都可以成功檢查更新，
不過只有幾個都會呈現「錯誤」，而直接用瀏覽器開連結則是能順利開啟。

範例網頁：
https://www.manhuagui.com/comic/28839/

錯誤訊息：
Start analyzing https://www.manhuagui.com/comic/28839/
Failed to check update
Thread crashed: <bound method BatchAnalyzer.analyze of <comiccrawler.batch_analyzer.BatchAnalyzer object at 0x000001EB353E3250>>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\worker\__init__.py", line 474, in wrap_worker
    self.ret = self.worker(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\comiccrawler\batch_analyzer.py", line 43, in analyze
    self.do_analyze()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\comiccrawler\batch_analyzer.py", line 59, in do_analyze
    Analyzer(mission).analyze()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\comiccrawler\analyzer.py", line 57, in analyze
    self.do_analyze()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\comiccrawler\analyzer.py", line 86, in do_analyze
    self.analyze_pages()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\comiccrawler\analyzer.py", line 107, in analyze_pages
    eps = list(self.mission.module.get_episodes(self.html, url))
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\comiccrawler\mods\seemh.py", line 79, in get_episodes
    ep_html = lzstring.decompress_from_base64(view_state)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\comiccrawler\mods\seemh.py", line 39, in decompress_from_base64
    return self.vm.call("LZString.decompressFromBase64", data)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\deno_vm\__init__.py", line 162, in call
    return self.communicate({
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\deno_vm\__init__.py", line 105, in communicate
    raise VMError(data["error"])
deno_vm.VMError: (vm-server) failed getting VM, id=null

**Comment by eight04** [comment]
ComicCrawler 版本？2024.1.4 測試正常

**Comment by Zivch** [comment]
2022.2.6

**Comment by eight04** [comment]
執行 `comiccrawler --version` 指令，可以顯示版本

**Comment by Zivch** [comment]
![螢幕擷取畫面 2024-01-09 214518](https://github.com/eight04/ComicCrawler/assets/38932324/289ae90b-557d-401a-b45f-b0f47fce4204)

**Comment by eight04** [comment]
按理來說，我們在 2023.10.11 才換成 deno_vm。
你的電腦中是否有兩個版本以上的 python？我猜是裝了多個版本的 python 跟 ComicCrawler。
可以執行 `where python`, `where comiccrawler` 確認

**Comment by Zivch** [comment]
我發現我在python 3.9下使用pip install comiccrawler，
安裝的版本都會是2022.2.6。
我把python 3.9解除安裝、改為3.12後，
就可以安裝2024.1.4的版本了。

不過問題還在。
範例網站：
https://www.manhuagui.com/comic/25586/

log:

Start analyzing https://www.manhuagui.com/comic/25586/
Thread crashed: <function DownloadManager.start_analyze.<locals>.analyze_thread at 0x000001356FAB1260>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\worker\__init__.py", line 483, in wrap_worker
    self.ret = self.worker(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\download_manager.py", line 171, in analyze_thread
    Analyzer(mission).analyze()
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\analyzer.py", line 57, in analyze
    self.do_analyze()
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\analyzer.py", line 86, in do_analyze
    self.analyze_pages()
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\analyzer.py", line 107, in analyze_pages
    eps = list(self.mission.module.get_episodes(self.html, url))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\comiccrawler\mods\seemh.py", line 79, in get_episodes
    ep_html = lzstring.decompress_from_base64(view_state)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\comiccrawler\mods\seemh.py", line 39, in decompress_from_base64
    return self.vm.call("LZString.decompressFromBase64", data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\deno_vm\__init__.py", line 162, in call
    return self.communicate({
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\deno_vm\__init__.py", line 105, in communicate
    raise VMError(data["error"])
deno_vm.VMError: (vm-server) failed getting VM, id=null

**Comment by Zivch** [comment]
謝謝eight04大大的幫忙！

我之前也都會用pip install upgrade (以及用upgrade-strategy eager)來更新，不過結果都一樣。

我剛剛自己手動拉下seemh.py，放入本地的mods取代舊黨後就解決問題了。
謝謝！
