### ISSUE TITLE
Manhuagui下載問題回報

### ISSUE THREAD

**Issue by Zivch** [eight04/ComicCrawler#374]
今天下午更新2024.3.25之後，還可以下載。
不過晚上就遇到錯誤。
相同的網址用瀏覽器可以打開，所以應該不是被鎖IP。
如果大大有空的話，還請幫忙看一下。

範例網站：
https://www.manhuagui.com/comic/30477/

錯誤訊息：
Downloading 单话 第01话 page 1: file://i.hamreus.com/ps2/z/zjcwzqljss_xhw/第01话/embed0000_HD.jpg.webp?e=1712454760&m=drmqXFP7A-uQ4ESW9tkkBw

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\crawler.py", line 392, in error_loop
    process()
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\crawler.py", line 363, in download
    crawler.download_image()
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\crawler.py", line 98, in download_image
    result = self.downloader.img(
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\module_grabber.py", line 18, in img
    return self.grab(grabimg, url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\module_grabber.py", line 34, in grab
    return grab_method(url, **new_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\grabber.py", line 250, in grabimg
    r = grabber(*args, header=header, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\grabber.py", line 99, in grabber
    r = await_(do_request, s, url, proxies, retry, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\worker\__init__.py", line 943, in wrapped
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\worker\__init__.py", line 962, in await_
    return async_(callback, *args, **kwargs).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\worker\__init__.py", line 691, in get
    raise err
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\worker\__init__.py", line 483, in wrap_worker
    self.ret = self.worker(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\grabber.py", line 112, in do_request
    r = s.request(kwargs.pop("method", "GET"), url, timeout=(22, 60),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 697, in send
    adapter = self.get_adapter(url=request.url)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 794, in get_adapter
    raise InvalidSchema(f"No connection adapters were found for {url!r}")
requests.exceptions.InvalidSchema: No connection adapters were found for 'file://i.hamreus.com/ps2/z/zjcwzqljss_xhw/第01话/embed0000_HD.jpg.webp?e=1712454760&m=drmqXFP7A-uQ4ESW9tkkBw'
wait 10 seconds...

**Comment by eight04** [comment]
Fixed in 2024.4.2
