### ISSUE TITLE
無法開啟圖形使用者介面

### ISSUE THREAD

**Issue by Zivch** [eight04/ComicCrawler#383]
打入comiccrawler gui後，出現下列訊息

C:\Users\user>comiccrawler gui
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Scripts\comiccrawler.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\cli.py", line 57, in console_init
    from .gui.main_window import MainWindow
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\gui\main_window.py", line 15, in <module>
    from ..mods import list_domain, get_module, load_config
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\mods\__init__.py", line 14, in <module>
    from ..config import config
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\config.py", line 10, in <module>
    import yt_dlp.cookies
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\__init__.py", line 18, in <module>
    from .cookies import SUPPORTED_BROWSERS, SUPPORTED_KEYRINGS
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\cookies.py", line 23, in <module>
    from .aes import (
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\aes.py", line 5, in <module>
    from .dependencies import Cryptodome
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\dependencies\__init__.py", line 60, in <module>
    import urllib3
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\__init__.py", line 18, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 990, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1123, in get_code
  File "<frozen importlib._bootstrap_external>", line 752, in _compile_bytecode
ValueError: bad marshal data (unknown type code)

**Comment by Zivch** [comment]
已解決。
請chatgpt幫忙疑難排除，
進行下列指令就可以開啟GUI。
pip uninstall yt-dlp urllib3
pip cache purge
pip install yt-dlp urllib3 --no-cache-dir

**Comment by eight04** [comment]
你更新時有加上 `--upgrade-strategy eager` 參數嗎？

**Comment by Zivch** [comment]
> 你更新時有加上 `--upgrade-strategy eager` 參數嗎？

有的。習慣性每次都會加上。
