### ISSUE TITLE
自行修改library.json之後gui開不起來

### ISSUE THREAD

**Issue by kesdoputr** [eight04/ComicCrawler#387]
你好，因為8comic有些以前的網址都只會直接跳回首頁

剛剛把library.json開起來想全取代成www.8comic.com，不過取代完之後gui就開不起來
試著只把其中一個
https://comicbus.com/html/15881.html
改成
https://www.8comic.com/html/15881.html

想開gui就會出現以下錯誤，還是說不能直接去改library只能手動一個一個重新加嗎？
感謝回答m(_ _)m
```
C:\Users\User\Desktop\movie>comiccrawler gui
Failed to load session!
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\User\AppData\Local\Programs\Python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\AppData\Local\Programs\Python\Scripts\comiccrawler.exe\__main__.py", line 7, in <module>
  File "C:\Users\User\AppData\Local\Programs\Python\lib\site-packages\comiccrawler\cli.py", line 57, in console_init
    from .gui.main_window import MainWindow
  File "C:\Users\User\AppData\Local\Programs\Python\lib\site-packages\comiccrawler\gui\main_window.py", line 23, in <module>
    from ..download_manager import download_manager
  File "C:\Users\User\AppData\Local\Programs\Python\lib\site-packages\comiccrawler\download_manager.py", line 31, in <module>
    from .mission_manager import mission_manager
  File "C:\Users\User\AppData\Local\Programs\Python\lib\site-packages\comiccrawler\mission_manager.py", line 196, in <module>
    mission_manager = MissionManager()
  File "C:\Users\User\AppData\Local\Programs\Python\lib\site-packages\comiccrawler\mission_manager.py", line 30, in __init__
    self.load()
  File "C:\Users\User\AppData\Local\Programs\Python\lib\site-packages\comiccrawler\mission_manager.py", line 68, in load
    self._load()
  File "C:\Users\User\AppData\Local\Programs\Python\lib\site-packages\comiccrawler\mission_manager.py", line 117, in _load
    self.library[url] = self.pool[url]
KeyError: 'https://www.8comic.com/html/15881.html'
```

**Comment by kesdoputr** [comment]
自己補，同時也改了pool.json和view.json好像就可以了，先把這個issue關了m(_ _)m
