### ISSUE TITLE
twitter 解析錯誤 Cookie ct0 not found

### ISSUE THREAD

**Issue by x2443120** [eight04/ComicCrawler#389]
版本已更新到最新，也試過更新填入對應網址的curl指令
都會出現解析錯誤 Cookie ct0 not found

Start analyzing https://twitter.com/Man_SU_11/media
Thread crashed: <function DownloadManager.start_analyze.<locals>.analyze_thread at 0x0000011AFFFD48B0>
Traceback (most recent call last):
  File "C:\Users\qaz24\AppData\Local\Programs\Python\Python310\lib\site-packages\worker\__init__.py", line 483, in wrap_worker
    self.ret = self.worker(*args, **kwargs)
  File "C:\Users\qaz24\AppData\Local\Programs\Python\Python310\lib\site-packages\comiccrawler\download_manager.py", line 198, in analyze_thread
    Analyzer(mission).analyze()
  File "C:\Users\qaz24\AppData\Local\Programs\Python\Python310\lib\site-packages\comiccrawler\analyzer.py", line 58, in analyze
    self.do_analyze()
  File "C:\Users\qaz24\AppData\Local\Programs\Python\Python310\lib\site-packages\comiccrawler\analyzer.py", line 87, in do_analyze
    self.analyze_pages()
  File "C:\Users\qaz24\AppData\Local\Programs\Python\Python310\lib\site-packages\comiccrawler\analyzer.py", line 108, in analyze_pages
    eps = list(self.mission.module.get_episodes(self.html, url))
  File "C:\Users\qaz24\AppData\Local\Programs\Python\Python310\lib\site-packages\comiccrawler\mods\twitter.py", line 59, in get_episodes
    init_api_session()
  File "C:\Users\qaz24\AppData\Local\Programs\Python\Python310\lib\site-packages\comiccrawler\mods\twitter.py", line 52, in init_api_session
    "x-csrf-token": get_cookie(session.cookies, "ct0", domain="x.com"),
  File "C:\Users\qaz24\AppData\Local\Programs\Python\Python310\lib\site-packages\comiccrawler\util.py", line 111, in get_cookie
    raise ValueError(f"Cookie {name} not found")
ValueError: Cookie ct0 not found

**Comment by eight04** [comment]
在2024.3.25之後，Comic Crawler會從瀏覽器讀取Cookie。請至setting.ini設定`browser`和`browser_profile`。
```
; 從瀏覽器中讀取 cookies，使用 yt-dlp 的 cookies-from-browser
; https://github.com/yt-dlp/yt-dlp/blob/e5d4f11104ce7ea1717a90eea82c0f7d230ea5d5/yt_dlp/cookies.py#L109
browser = firefox

; 瀏覽器 profile 的名稱
browser_profile = act3nn7e.default
```
不過我只在Firefox測試過這功能，還沒試過Chrome

**Comment by x2443120** [comment]
這幾天才遇到這個問題所以之前都照常使用，問題解決了，非常感謝
