### ISSUE TITLE
exhentai無法下載

### ISSUE THREAD

**Issue by seiya2000000** [eight04/ComicCrawler#392]
exhentai 下載時出現下列錯誤 
```
Start downloading Keijo!!!!!!!! (1038794/4f48efcd59)
total 1 episode.
Downloading ep image
Traceback (most recent call last):
<unknown>:1: SyntaxWarning: invalid escape sequence '\('
  File "C:\Users\kazamiw\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\crawler.py", line 393, in error_loop
    process()
  File "C:\Users\kazamiw\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\crawler.py", line 342, in download
    crawler.init()
  File "C:\Users\kazamiw\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\crawler.py", line 58, in init
    self.init_images(self.ep.current_page - 1)
  File "C:\Users\kazamiw\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\crawler.py", line 65, in init_images
    self.get_images()
  File "C:\Users\kazamiw\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\crawler.py", line 235, in get_images
    images = self.mod.get_images(
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kazamiw\AppData\Local\Programs\Python\Python312\Lib\site-packages\comiccrawler\mods\exh.py", line 52, in get_images
    nl = re.search("nl\('([^)]+)'\)", html).group(1)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by eight04** [comment]
Python 3.13
ComicCrawler 2024.11.14 
Windows 10
測試沒問題

你試試把exh.py 52行，pattern的前面加一個`r`:
```py
	nl = re.search(r"nl\('([^)]+)'\)", html).group(1)
```
或是直接刪掉那行

**Comment by seiya2000000** [comment]
nl = re.search("nl\('([^)]+)'\)", html).group(1)

把這一行刪掉，啟動 comiccrawler gui 會出現錯誤 

改成
	nl = re.search(r"nl\('([^)]+)'\)", html).group(1)
一樣的錯誤
Traceback (most recent call last):
  File "C:\Users\kazamiw\AppData\Local\Programs\Python\Python313\Lib\site-packages\comiccrawler\crawler.py", line 393, in error_loop
    process()
    ~~~~~~~^^
  File "C:\Users\kazamiw\AppData\Local\Programs\Python\Python313\Lib\site-packages\comiccrawler\crawler.py", line 342, in download
    crawler.init()
    ~~~~~~~~~~~~^^
  File "C:\Users\kazamiw\AppData\Local\Programs\Python\Python313\Lib\site-packages\comiccrawler\crawler.py", line 58, in init
    self.init_images(self.ep.current_page - 1)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kazamiw\AppData\Local\Programs\Python\Python313\Lib\site-packages\comiccrawler\crawler.py", line 65, in init_images
    self.get_images()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\kazamiw\AppData\Local\Programs\Python\Python313\Lib\site-packages\comiccrawler\crawler.py", line 235, in get_images
    images = self.mod.get_images(
        self.html,
        self.ep.current_url
    )
  File "C:\Users\kazamiw\AppData\Local\Programs\Python\Python313\Lib\site-packages\comiccrawler\mods\exh.py", line 52, in get_images
    nl = re.search(r"nl\('([^)]+)'\)", html).group(1)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by seiya2000000** [comment]
exh.html 是空的，目前的電腦環境 WIn 10，deno 2.0.6，Python 3.13.0
錯誤訊息如下
Start downloading LOVELY×CATION1&2 ビジュアルファンブック (1054985/d2045a3bc3)
total 1 episode.
Downloading ep image
Traceback (most recent call last):
<unknown>:2: SyntaxWarning: invalid escape sequence '\('
<unknown>:1: SyntaxWarning: invalid escape sequence '\('
  File "C:\Users\kazamiw\AppData\Local\Programs\Python\Python313\Lib\site-packages\comiccrawler\crawler.py", line 393, in error_loop
    process()
    ~~~~~~~^^
  File "C:\Users\kazamiw\AppData\Local\Programs\Python\Python313\Lib\site-packages\comiccrawler\crawler.py", line 342, in download
    crawler.init()
    ~~~~~~~~~~~~^^
  File "C:\Users\kazamiw\AppData\Local\Programs\Python\Python313\Lib\site-packages\comiccrawler\crawler.py", line 58, in init
    self.init_images(self.ep.current_page - 1)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kazamiw\AppData\Local\Programs\Python\Python313\Lib\site-packages\comiccrawler\crawler.py", line 65, in init_images
    self.get_images()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\kazamiw\AppData\Local\Programs\Python\Python313\Lib\site-packages\comiccrawler\crawler.py", line 235, in get_images
    images = self.mod.get_images(
        self.html,
        self.ep.current_url
    )
  File "C:\Users\kazamiw\AppData\Local\Programs\Python\Python313\Lib\site-packages\comiccrawler\mods\exh.py", line 55, in get_images
    nl = re.search("nl\('([^)]+)'\)", html).group(1)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by eight04** [comment]
可以加入新的URL嗎？是不是沒登入？

**Comment by seiya2000000** [comment]
檢查了一下，cookie的值跟瀏覽器看到的一樣，新增連結也不行
[e紳士]
cookie_ipb_member_id = xxxx
cookie_ipb_pass_hash = xxxx                
original = true
cookie_igneous = mystery

**Comment by eight04** [comment]
如果可以的話，先用設定檔的browser, browser_profile來登入
https://github.com/eight04/ComicCrawler?tab=readme-ov-file#%E9%97%9C%E6%96%BC%E9%9C%80%E8%A6%81%E7%99%BB%E5%85%A5%E7%9A%84%E7%B6%B2%E7%AB%99

以後可能會加入其它比較方便的方法，不用手動一項項輸入cookie，但可能就要依賴browser extension

**Comment by seiya2000000** [comment]
用設定檔的browser, browser_profile
可以下載了，
謝謝

**Comment by eggnog5566** [comment]
問題已解決
環境：MacOSX 14.5、python3.11、deno 2.0.6

一樣遇錯誤
Thread crashed: <function DownloadManager.start_analyze.<locals>.analyze_thread at 0x11e7b4f40>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/worker/__init__.py", line 483, in wrap_worker
    self.ret = self.worker(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/comiccrawler/download_manager.py", line 198, in analyze_thread
    Analyzer(mission).analyze()
  File "/usr/local/lib/python3.11/site-packages/comiccrawler/analyzer.py", line 58, in analyze
    self.do_analyze()
  File "/usr/local/lib/python3.11/site-packages/comiccrawler/analyzer.py", line 84, in do_analyze
    self.mission.title = self.mission.module.get_title(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/comiccrawler/mods/exh.py", line 38, in get_title
    title = re.findall("<h1 id=\"g(j|n)\">(.+?)</h1>", html)[-1][1]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range



最後更動以下設定解決了

升級 deno 版本
brew upgrade deno
deno 2.0.1 -> 2.0.6

profile 使用
browser = firefox
browser_profile =
firefox
about:profiles 裡的設定檔

謝謝 eight04大

**Comment by eight04** [comment]
Improved login error at [60509d7](https://github.com/eight04/ComicCrawler/commit/60509d721d9971162e027a5404ceb045a9ed23a4)
