### ISSUE TITLE
更新到最新之後gui叫不出來？

### ISSUE THREAD

**Issue by kesdoputr** [eight04/ComicCrawler#52]
您好，我剛更新到最新的4.22

不過使用comiccrawler gui的指令時沒出現介面，下面是給出來的訊息

Traceback (most recent call last):
  File "c:\python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\comiccrawler.exe\__main__.py", line 9, in <module>
  File "c:\python34\lib\site-packages\comiccrawler\__init__.py", line 58, in con
sole_init
    main()
  File "c:\python34\lib\site-packages\comiccrawler\gui\__init__.py", line 6, in
main
    from .main_window import MainWindow
  File "c:\python34\lib\site-packages\comiccrawler\gui\main_window.py", line 14,
 in <module>
    from ..mods import list_domain, get_module, load_config, domain_index
  File "c:\python34\lib\site-packages\comiccrawler\mods\__init__.py", line 40, i
n <module>
    mods.add(import_module("comiccrawler.mods." + name))
  File "c:\python34\lib\importlib\__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\python34\lib\site-packages\comiccrawler\mods\aacomic.py", line 14, in
 <module>
    from ..core import Episode, grabhtml, CycleList
  File "c:\python34\lib\site-packages\comiccrawler\core\__init__.py", line 783
    self.mission.episodes = [*old_eps]
                              ^
SyntaxError: can use starred expression only as assignment target

**Comment by eight04** [comment]
我用到了比較新的 syntax，會在下個版本修正。很急的話可以先把 Python 更新到最新版。

**Comment by eight04** [comment]
於 2017.4.23 修正
