### ISSUE TITLE
ikanman 看漫畫 下載失敗

### ISSUE THREAD

**Issue by bluelovers** [eight04/ComicCrawler#57]
ikanman 看漫畫 下載失敗

```
IndexError: string index out of range
Start download
Start downloading
total 3 episode.
Downloading ep 第01卷
Thread crashed: <function download at 0x0000021AB991AD90>
Traceback (most recent call last):
  File "python\python36\lib\site-packages\worker\__init__.py", line 384, in wrap_worker
    self.ret = self.worker(*args, **kwargs)
  File "python\python36\lib\site-packages\comiccrawler\core\__init__.py", line 180, in download
    crawl(mission, savepath)
  File "cpython\python36\lib\site-packages\comiccrawler\core\__init__.py", line 217, in crawl
    crawler = Crawler(mission, ep, savepath)
  File "python\python36\lib\site-packages\comiccrawler\core\__init__.py", line 352, in __init__
    self.savepath = SavePath(savepath, mission, ep)
  File "python\python36\lib\site-packages\comiccrawler\core\__init__.py", line 290, in __init__
    self.mission_title = escape(mission.title)
  File "python\python36\lib\site-packages\comiccrawler\core\__init__.py", line 168, in safefilepath
    if s[-1] == ".":
IndexError: string index out of range
```

**Comment by eight04** [comment]
網址？看起來任務名稱是空的

**Comment by bluelovers** [comment]
http://tw.ikanman.com/comic/2017/17189.html

**Comment by eight04** [comment]
請用章節列表的網址
http://tw.ikanman.com/comic/2017/

**Comment by bluelovers** [comment]
FileNotFoundError: [WinError 2] 系統找不到指定的檔案。
Traceback (most recent call last):
  File "python\python36\lib\site-packages\comiccrawler\core\__init__.py", line 579, in error_loop
    process()
  File "python\python36\lib\site-packages\comiccrawler\core\__init__.py", line 529, in download
    crawler.init()
  File "python\python36\lib\site-packages\comiccrawler\core\__init__.py", line 370, in init
    self.init_images(self.ep.current_page - 1)
  File "python\python36\lib\site-packages\comiccrawler\core\__init__.py", line 377, in init_images
    self.get_images()
  File "python\python36\lib\site-packages\comiccrawler\core\__init__.py", line 496, in get_images
    self.ep.current_url
  File "python\python36\lib\site-packages\comiccrawler\mods\seemh.py", line 76, in get_images
    with VM(js) as vm:
  File "python\python36\lib\site-packages\node_vm2\__init__.py", line 115, in __init__
    super().__init__(server)
  File "python\python36\lib\site-packages\node_vm2\__init__.py", line 53, in __init__
    server = default_bridge()
  File "python\python36\lib\site-packages\node_vm2\__init__.py", line 35, in default_bridge
    DEFAULT_BRIDGE = VMServer().start()
  File "python\python36\lib\site-packages\node_vm2\__init__.py", line 389, in start
    self.process = Popen(args, bufsize=0, stdin=PIPE, stdout=PIPE)
  File "python\python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "python\python36\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系統找不到指定的檔案。

![2017-05-17-14-58-55-1](https://cloud.githubusercontent.com/assets/167966/26142105/ae84a150-3b11-11e7-9667-46cbd843fc7f.jpg)

**Comment by eight04** [comment]
你沒有安裝 Node.js
https://github.com/eight04/ComicCrawler#install-nodejs

**Comment by bluelovers** [comment]
原來如此 之前為了 找是不是 msys2 裡面的 python 衝突到 所以把 PATH 裡面的 nodejs 路徑也一起刪除了

謝謝
