### ISSUE TITLE
ikanman的某个章节下载失败

### ISSUE THREAD

**Issue by wby238** [eight04/ComicCrawler#60]
[不正经的魔术讲师与禁忌教典](http://www.ikanman.com/comic/18784/)
下载最新的“第19.1回”时，从昨天就试到了现在，一直下载失败。下载其他作品没问题，在线漫画浏览正常。
出错log一直重复以下：
```python
Downloading 第19.1回 page 22: http://i.yogajx.com/ps4/b/bzjdmsjsyjjjd_ytl/第19.1
回/zz

Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\comiccrawler\core\__init__.p
y", line 579, in error_loop
    process()
  File "c:\program files\python36\lib\site-packages\comiccrawler\core\__init__.p
y", line 551, in download
    crawler.download_image()
  File "c:\program files\python36\lib\site-packages\comiccrawler\core\__init__.p
y", line 400, in download_image
    self.image.url, referer=self.ep.current_url)
  File "c:\program files\python36\lib\site-packages\comiccrawler\core\__init__.p
y", line 256, in img
    **kwargs
  File "c:\program files\python36\lib\site-packages\comiccrawler\core\grabber.py
", line 157, in grabimg
    return ImgResult(grabber(*args, **kwargs))
  File "c:\program files\python36\lib\site-packages\comiccrawler\core\grabber.py
", line 74, in grabber
    r = await_(do_request, s, url, params, raise_429)
  File "c:\program files\python36\lib\site-packages\worker\__init__.py", line 64
5, in wrapped
    return f(*args, **kwargs)
  File "c:\program files\python36\lib\site-packages\worker\__init__.py", line 65
7, in await_
    return async_(callback, *args, **kwargs).get()
  File "c:\program files\python36\lib\site-packages\worker\__init__.py", line 51
1, in get
    raise err
  File "c:\program files\python36\lib\site-packages\worker\__init__.py", line 38
4, in wrap_worker
    self.ret = self.worker(*args, **kwargs)
  File "c:\program files\python36\lib\site-packages\comiccrawler\core\grabber.py
", line 89, in do_request
    r.raise_for_status()
  File "c:\program files\python36\lib\site-packages\requests\models.py", line 90
9, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://i.yog
ajx.com/ps4/b/bzjdmsjsyjjjd_ytl/%E7%AC%AC19.1%E5%9B%9E/zz
```

**Comment by eight04** [comment]
這應該是網站自己的問題，我也看不到第22頁︰
http://www.ikanman.com/comic/18784/302419.html#p=22

**Comment by wby238** [comment]
我刚刚试了下，22页打开正常啊……

**Comment by eight04** [comment]
我的瀏覽器是用 Firefox，所以打不開。

我建議︰
1. 直接略過該章節
2. 下載 webp 格式。把設定檔中的 nowebp = true 改成 false
