### ISSUE TITLE
comicbus下載問題

### ISSUE THREAD

**Issue by kesdoputr** [eight04/ComicCrawler#62]
您好，更新到5.19後可以檢查更新了，不過剛剛有幾本漫畫
檢查有新話數，去網頁上看也確實有那個話數存在，不過抓
的時候顯示以下錯誤訊息抓不下來，舉例食戟之靈：
http://www.comicbus.com/html/9337.html
comiccrawler顯示有新集數215話
下載的時候一直抓不下來

Start download 食戟之靈
Start downloading 食戟之靈
total 217 episode.
Downloading ep 第215話
Session saved
Traceback (most recent call last):
  File "c:\python34\lib\site-packages\comiccrawler\core\__init__.py", line 579,
in error_loop
    process()
  File "c:\python34\lib\site-packages\comiccrawler\core\__init__.py", line 529,
in download
    crawler.init()
  File "c:\python34\lib\site-packages\comiccrawler\core\__init__.py", line 370,
in init
    self.init_images(self.ep.current_page - 1)
  File "c:\python34\lib\site-packages\comiccrawler\core\__init__.py", line 377,
in init_images
    self.get_images()
  File "c:\python34\lib\site-packages\comiccrawler\core\__init__.py", line 496,
in get_images
    self.ep.current_url
  File "c:\python34\lib\site-packages\comiccrawler\mods\eight.py", line 114, in
get_images
    pages = int(ss(code[7:10]))
ValueError: invalid literal for int() with base 10: ''

補充：抓源君物語的時候error好像不大一樣
http://www.comicbus.com/html/8323.html

Start download 源君物語
Start downloading 源君物語
total 256 episode.
Downloading ep 第254話
Downloading 第254話 page 1: http://img6.8comic.com/q/8323/254/001_cdg.jpg

Traceback (most recent call last):
  File "c:\python34\lib\site-packages\requests\packages\urllib3\connection.py",
line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "c:\python34\lib\site-packages\requests\packages\urllib3\util\connection.
py", line 83, in create_connection
    raise err
  File "c:\python34\lib\site-packages\requests\packages\urllib3\util\connection.
py", line 73, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python34\lib\site-packages\requests\packages\urllib3\connectionpool.p
y", line 600, in urlopen
    chunked=chunked)
  File "c:\python34\lib\site-packages\requests\packages\urllib3\connectionpool.p
y", line 356, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "c:\python34\lib\http\client.py", line 1137, in request
    self._send_request(method, url, body, headers)
  File "c:\python34\lib\http\client.py", line 1182, in _send_request
    self.endheaders(body)
  File "c:\python34\lib\http\client.py", line 1133, in endheaders
    self._send_output(message_body)
  File "c:\python34\lib\http\client.py", line 963, in _send_output
    self.send(msg)
  File "c:\python34\lib\http\client.py", line 898, in send
    self.connect()
  File "c:\python34\lib\site-packages\requests\packages\urllib3\connection.py",
line 166, in connect
    conn = self._new_conn()
  File "c:\python34\lib\site-packages\requests\packages\urllib3\connection.py",
line 146, in _new_conn
    (self.host, self.timeout))
requests.packages.urllib3.exceptions.ConnectTimeoutError: (<requests.packages.ur
llib3.connection.HTTPConnection object at 0x03537DD0>, 'Connection to img6.8comi
c.com timed out. (connect timeout=20)')

During handling of the above exception, another exception occurred:

**Comment by eight04** [comment]
於 2017.5.22 修正。請在更新後把 comicbus 任務砍掉再重分析。

這個 bug 是因為程式抓到了錯誤的 url。這是程式抓到的︰
http://v.nowcomic.com/online/manga_9337.html?ch=215
這是正確的︰
http://v.comicbus.com/online/comic-9337.html?ch=215
