### ISSUE TITLE
Failed to load session!

### ISSUE THREAD

**Issue by topspeculator** [eight04/ComicCrawler#64]
您好，
我用記事本重新編輯了library.json、pool.json
將其中的網址取代，如www.hhssee.com => www.hhmmoo.com
存檔後，執行comiccrawler gui
出現下列錯誤訊息，請您指點（我有嚐試復原網址取代，但無效）
感恩。
Failed to load session!
Traceback (most recent call last):
  File "c:\python34\lib\runpy.py", line 170, in _run_module_as_main    "__main__", mod_spec)
  File "c:\python34\lib\runpy.py", line 85, in _run_code    exec(code, run_globals)
  File "C:\Python34\Scripts\comiccrawler.exe\__main__.py", line 9, in <module>
  File "c:\python34\lib\site-packages\comiccrawler\__init__.py", line 58, in console_init    main()
  File "c:\python34\lib\site-packages\comiccrawler\gui\__init__.py", line 6, inmain    from .main_window import MainWindow
  File "c:\python34\lib\site-packages\comiccrawler\gui\main_window.py", line 21, in <module>    from ..download_manager import download_manager
  File "c:\python34\lib\site-packages\comiccrawler\download_manager.py", line 21, in <module>
    from .mission_manager import mission_manager, init_episode, uninit_episode
  File "c:\python34\lib\site-packages\comiccrawler\mission_manager.py", line 297, in <module>
    mission_manager = MissionManager()
  File "c:\python34\lib\site-packages\comiccrawler\mission_manager.py", line 132, in __init__
    self.load()
  File "c:\python34\lib\site-packages\comiccrawler\mission_manager.py", line 170, in load
    self._load()
  File "c:\python34\lib\site-packages\comiccrawler\mission_manager.py", line 211, in _load
    mission = MissionProxy(Mission(**m_data))
  File "c:\python34\lib\site-packages\comiccrawler\core\__init__.py", line 48, in __init__    raise ModuleError("Get module failed!")
comiccrawler.error.ModuleError: Get module failed!

**Comment by eight04** [comment]
`Get module failed!` 指的是 Comic Crawler 無法為特定的任務（網址）找到相關對應的模組。目前支援的網域請參考 https://github.com/eight04/ComicCrawler#supported-domains

換句話說，在你修改過的 `pool.json` 和 `library.json` 中，`www.hhmmoo.com` 被認為是不支援的網站。有幾個解法︰

1. 由於那個網址只是汗汗換了域名，可以試著直接修改 [`hhxiee.py` 中的第 17 行](https://github.com/eight04/ComicCrawler/blob/master/comiccrawler/mods/hhxiee.py#L17)，把 `www.hhmmoo.com` 也加入 `domain` 的陣列中。
2. 把所有 `www.hhmmoo.com` 的任務改回 `www.hhssee.com`。但我試了一下，`www.hhssee.com` 連不上了？

額外說明一點，若你想修改任務的網址，只修改 `library.json` 和 `pool.json` 是不夠的。你需要修改的東西包括︰

1. `pool.json`，儲存任務的名稱、網址和下載狀態。修改任務的 url。
2. `library.json`（圖書館） 或 `view.json`（下載列表），儲存任務列表的順序。由於你修改了任務的 url，也必須修改這兩個檔案以對應到新的 url。
3. `pool` 資料夾內的章節資料︰
	* 修改檔名中的 hash。檔名為 `任務名稱 [6碼英數字].json`。其中的6碼英數字是 [對 url 編碼得到的 hash](https://github.com/eight04/ComicCrawler/blob/master/comiccrawler/mission_manager.py#L24)。由於修改了 url，hash 也會跟著改變。新的 hash 可以用類似的手法產生︰
		```
		import hashlib
		print(hashlib.sha1("新網址".encode("utf-8")).hexdigest()[:6])
		```
	* 修改檔案內的 url 和 current_url，分別是各章節的網址和「目前所下載之頁數」的網址。
		
綜合以上幾點，當一個任務換網址時要改的東西實在太多了。我建議直接將任務刪除後，重建一個新任務會比較快。

**Comment by topspeculator** [comment]
您好，謝謝指點
已用記事本，將library.json 和 pool.json中的hhssee.com及hhmmoo.com任務全數刪除存檔，已正常開啟。

另請教nowebp=true，意思是"不下載webp格式"，或是“下載webp格式但存成jpg“呢？

**Comment by eight04** [comment]
ikanman 會對不同的瀏覽器提供不同的檔案格式，參考 https://github.com/eight04/ComicCrawler/issues/31
