### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by DENISBruno** [eight04/ComicCrawler#65]
Error installing comiccrawler.
```
C:\Users\USRSUPORTE06>comiccrawler gui
Failed to load session!
Traceback (most recent call last):
  File "c:\users\usrsuporte06\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\usrsuporte06\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\USRSUPORTE06\AppData\Local\Programs\Python\Python36-32\Scripts\comiccrawler.exe\__main__.py", line 9, in <module>
  File "c:\users\usrsuporte06\appdata\local\programs\python\python36-32\lib\site-packages\comiccrawler\__init__.py", line 58, in console_init
    main()
  File "c:\users\usrsuporte06\appdata\local\programs\python\python36-32\lib\site-packages\comiccrawler\gui\__init__.py", line 6, in main
    from .main_window import MainWindow
  File "c:\users\usrsuporte06\appdata\local\programs\python\python36-32\lib\site-packages\comiccrawler\gui\main_window.py", line 21, in <module>
    from ..download_manager import download_manager
  File "c:\users\usrsuporte06\appdata\local\programs\python\python36-32\lib\site-packages\comiccrawler\download_manager.py", line 21, in <module>
    from .mission_manager import mission_manager, init_episode, uninit_episode
  File "c:\users\usrsuporte06\appdata\local\programs\python\python36-32\lib\site-packages\comiccrawler\mission_manager.py", line 297, in <module>
    mission_manager = MissionManager()
  File "c:\users\usrsuporte06\appdata\local\programs\python\python36-32\lib\site-packages\comiccrawler\mission_manager.py", line 132, in __init__
    self.load()
  File "c:\users\usrsuporte06\appdata\local\programs\python\python36-32\lib\site-packages\comiccrawler\mission_manager.py", line 170, in load
    self._load()
  File "c:\users\usrsuporte06\appdata\local\programs\python\python36-32\lib\site-packages\comiccrawler\mission_manager.py", line 179, in _load
    pool = load(profile("pool.json")) or []
  File "c:\users\usrsuporte06\appdata\local\programs\python\python36-32\lib\site-packages\comiccrawler\mission_manager.py", line 100, in load
    return json.load(fp)
  File "c:\users\usrsuporte06\appdata\local\programs\python\python36-32\lib\json\__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "c:\users\usrsuporte06\appdata\local\programs\python\python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "c:\users\usrsuporte06\appdata\local\programs\python\python36-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\usrsuporte06\appdata\local\programs\python\python36-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by eight04** [comment]
Looks like your `pool.json` is broken. Could you email the file to me?

If you don't need the data, you can just delete `pool.json`, `view.json`, and `library.json` so Comic Crawler could start up correctly.

**Comment by DENISBruno** [comment]
Where are these files?

**Comment by eight04** [comment]
`%USERPROFILE%\comiccrawler`

**Comment by DENISBruno** [comment]
It worked! Tks man!
