### ISSUE TITLE
Comicbus下載錯誤

### ISSUE THREAD

**Issue by kesdoputr** [eight04/ComicCrawler#69]
您好，使用的是最新的08.16版
在抓最新的海賊王
http://www.comicbus.com/html/103.html
875的時候出現錯誤

Start download 海賊王
Start downloading 海賊王
total 476 episode.
Downloading ep 第875話 女人的仁義
Traceback (most recent call last):
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 579, in
 error_loop
    process()
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 529, in
 download
    crawler.init()
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 370, in
 init
    self.init_images(self.ep.current_page - 1)
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 377, in
 init_images
    self.get_images()
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 496, in
 get_images
    self.ep.current_url
  File "c:\python\lib\site-packages\comiccrawler\mods\eight.py", line 79, in get
_images
    pages = int(ss(code[7:10]))
ValueError: invalid literal for int() with base 10: '9E'
Traceback (most recent call last):
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 579, in
 error_loop
    process()
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 529, in
 download
    crawler.init()
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 370, in
 init
    self.init_images(self.ep.current_page - 1)
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 377, in
 init_images
    self.get_images()
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 496, in
 get_images
    self.ep.current_url
  File "c:\python\lib\site-packages\comiccrawler\mods\eight.py", line 79, in get
_images
    pages = int(ss(code[7:10]))
ValueError: invalid literal for int() with base 10: '9E'

**Comment by eight04** [comment]
於 2017.8.20 修正。

**Comment by kesdoputr** [comment]
感謝修正
