### ISSUE TITLE
Sorry還是關於comicbus的問題

### ISSUE THREAD

**Issue by kesdoputr** [eight04/ComicCrawler#70]
更新到8.20後之前不能下載的海賊王可以正常下載了
也另外還下了三本更新的漫畫都正常，不過不知道是
不是特殊情況，這一本還是會有錯誤
http://www.comicbus.com/html/7294.html
跑出有更新的32話，下載的時候重複以下的訊息
Start download 飛翔的魔女
Start downloading 飛翔的魔女
total 33 episode.
Downloading ep 第32話
Traceback (most recent call last):
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 581, in
 error_loop
    process()
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 531, in
 download
    crawler.init()
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 372, in
 init
    self.init_images(self.ep.current_page - 1)
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 379, in
 init_images
    self.get_images()
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 498, in
 get_images
    self.ep.current_url
  File "c:\python\lib\site-packages\comiccrawler\mods\eight.py", line 62, in get
_images
    script = re.search('(var ch=.+?)spp\(\)', html, re.DOTALL).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 581, in
 error_loop
    process()
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 531, in
 download
    crawler.init()
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 372, in
 init
    self.init_images(self.ep.current_page - 1)
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 379, in
 init_images
    self.get_images()
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 498, in
 get_images
    self.ep.current_url
  File "c:\python\lib\site-packages\comiccrawler\mods\eight.py", line 62, in get
_images
    script = re.search('(var ch=.+?)spp\(\)', html, re.DOTALL).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by eight04** [comment]
舊版本反而可以下載這連結。看來 comicbus 的資料有多種模式啊。

**Comment by eight04** [comment]
於最新版修正

**Comment by kesdoputr** [comment]
感謝修正，目前在comicbus都正常下載^^
