### ISSUE TITLE
Comicbus有幾本漫畫下載有問題

### ISSUE THREAD

**Issue by kesdoputr** [eight04/ComicCrawler#74]
已更新到最新0826，剛剛抓comicbus的有幾本可以抓有幾本不行
這個站感覺有各種模式的樣子？

一拳超人：
http://www.comicbus.com/10406.html

Start download 一拳超人
Start downloading 一拳超人
total 124 episode.
Downloading ep 第121話
Traceback (most recent call last):
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 581, in
 error_loop
    process()
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 531, in
 download
    crawler.init()
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 372, in
 init
    self.init_images(self.ep.current_page - 1)
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 379, in
 init_images
    self.get_images()
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 498, in
 get_images
    self.ep.current_url
  File "c:\python\lib\site-packages\comiccrawler\mods\eight.py", line 58, in get
_images
    nview = re.search('src="([^"]*nview\.js)"', html).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 581, in
 error_loop
    process()
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 531, in
 download
    crawler.init()
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 372, in
 init
    self.init_images(self.ep.current_page - 1)
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 379, in
 init_images
    self.get_images()
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 498, in
 get_images
    self.ep.current_url
  File "c:\python\lib\site-packages\comiccrawler\mods\eight.py", line 58, in get
_images
    nview = re.search('src="([^"]*nview\.js)"', html).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

異世界食堂：
http://www.comicbus.com/html/14706.html

Start download 異世界食堂
Start downloading 異世界食堂
total 9 episode.
Downloading ep 第10話
Traceback (most recent call last):
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 581, in
 error_loop
    process()
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 531, in
 download
    crawler.init()
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 372, in
 init
    self.init_images(self.ep.current_page - 1)
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 379, in
 init_images
    self.get_images()
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 498, in
 get_images
    self.ep.current_url
  File "c:\python\lib\site-packages\comiccrawler\mods\eight.py", line 58, in get
_images
    nview = re.search('src="([^"]*nview\.js)"', html).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 581, in
 error_loop
    process()
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 531, in
 download
    crawler.init()
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 372, in
 init
    self.init_images(self.ep.current_page - 1)
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 379, in
 init_images
    self.get_images()
  File "c:\python\lib\site-packages\comiccrawler\core\__init__.py", line 498, in
 get_images
    self.ep.current_url
  File "c:\python\lib\site-packages\comiccrawler\mods\eight.py", line 58, in get
_images
    nview = re.search('src="([^"]*nview\.js)"', html).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by eight04** [comment]
於 2017.8.31 修正。
