### ISSUE TITLE
Can't download from cartoonmad

### ISSUE THREAD

**Issue by obxyann** [eight04/ComicCrawler#81]
After upgrade from '2017.3.9' to 2017.9.9 It failed to download any link from cartoonmad.
link: http://www.cartoonmad.com/comic/3209.html
...
Traceback (most recent call last):
  File "c:\python36-32\lib\site-packages\comiccrawler\core\__init__.py", line 581, in error_loop
    process()
  File "c:\python36-32\lib\site-packages\comiccrawler\core\__init__.py", line 531, in download
    crawler.init()
....

**Comment by eight04** [comment]
於 2017.11.29 修正。
