### ISSUE TITLE
Tumblr下載錯誤

### ISSUE THREAD

**Issue by chenhan200** [eight04/ComicCrawler#84]
經瀏覽器測試
把圖片網址https改成http應該就可以正常下載了

Downloading 67855574951 page 1: https://data.tumblr.com/27194cbe1caa57eb631b9d71
82b371fd/tumblr_mwq5eb4B1i1t3nnako1_raw.jpg

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 601, in u
rlopen
    chunked=chunked)
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 346, in _
make_request
    self._validate_conn(conn)
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 850, in _
validate_conn
    conn.connect()
  File "C:\Python34\lib\site-packages\urllib3\connection.py", line 346, in conne
ct
    _match_hostname(cert, self.assert_hostname or hostname)
  File "C:\Python34\lib\site-packages\urllib3\connection.py", line 356, in _matc
h_hostname
    match_hostname(cert, asserted_hostname)
  File "C:\Python34\lib\site-packages\urllib3\packages\ssl_match_hostname\_imple
mentation.py", line 150, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
urllib3.packages.ssl_match_hostname._implementation.CertificateError: hostname '
data.tumblr.com' doesn't match either of 's3.amazonaws.com', '*.s3.amazonaws.com
', '*.s3.dualstack.us-east-1.amazonaws.com', 's3.dualstack.us-east-1.amazonaws.c
om', '*.s3.us-east-1.amazonaws.com', 's3.us-east-1.amazonaws.com'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 639, in u
rlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Python34\lib\site-packages\urllib3\util\retry.py", line 388, in incre
ment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='data.tumblr.com', po
rt=443): Max retries exceeded with url: /27194cbe1caa57eb631b9d7182b371fd/tumblr
_mwq5eb4B1i1t3nnako1_raw.jpg (Caused by SSLError(CertificateError("hostname 'dat
a.tumblr.com' doesn't match either of 's3.amazonaws.com', '*.s3.amazonaws.com',
'*.s3.dualstack.us-east-1.amazonaws.com', 's3.dualstack.us-east-1.amazonaws.com'
, '*.s3.us-east-1.amazonaws.com', 's3.us-east-1.amazonaws.com'",),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\comiccrawler\core\__init__.py", line 581,
in error_loop
    process()
  File "C:\Python34\lib\site-packages\comiccrawler\core\__init__.py", line 553,
in download
    crawler.download_image()
  File "C:\Python34\lib\site-packages\comiccrawler\core\__init__.py", line 402,
in download_image
    self.image.url, referer=self.ep.current_url)
  File "C:\Python34\lib\site-packages\comiccrawler\core\__init__.py", line 258,
in img
    **kwargs
  File "C:\Python34\lib\site-packages\comiccrawler\core\grabber.py", line 171, i
n grabimg
    return ImgResult(grabber(*args, **kwargs))
  File "C:\Python34\lib\site-packages\comiccrawler\core\grabber.py", line 80, in
 grabber
    r = await_(do_request, s, url, params, proxies, method, data, raise_429)
  File "C:\Python34\lib\site-packages\worker\__init__.py", line 645, in wrapped
    return f(*args, **kwargs)
  File "C:\Python34\lib\site-packages\worker\__init__.py", line 657, in await_
    return async_(callback, *args, **kwargs).get()
  File "C:\Python34\lib\site-packages\worker\__init__.py", line 511, in get
    raise err
  File "C:\Python34\lib\site-packages\worker\__init__.py", line 384, in wrap_wor
ker
    self.ret = self.worker(*args, **kwargs)
  File "C:\Python34\lib\site-packages\comiccrawler\core\grabber.py", line 90, in
 do_request
    data=data, proxies=proxies)
  File "C:\Python34\lib\site-packages\requests\sessions.py", line 508, in reques
t
    resp = self.send(prep, **send_kwargs)
  File "C:\Python34\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python34\lib\site-packages\requests\adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='data.tumblr.com', port=4
43): Max retries exceeded with url: /27194cbe1caa57eb631b9d7182b371fd/tumblr_mwq
5eb4B1i1t3nnako1_raw.jpg (Caused by SSLError(CertificateError("hostname 'data.tu
mblr.com' doesn't match either of 's3.amazonaws.com', '*.s3.amazonaws.com', '*.s
3.dualstack.us-east-1.amazonaws.com', 's3.dualstack.us-east-1.amazonaws.com', '*
.s3.us-east-1.amazonaws.com', 's3.us-east-1.amazonaws.com'",),))

**Comment by eight04** [comment]
這有點像 tumblr 自己的問題。我記得之前修 #82 時還是正常的？

我覺得自動把 HTTPS 轉成 HTTP 是個不恰當的行為，也許可以加一個選項 `full_size_with_http = True`

**Comment by chenhan200** [comment]
full_size_with_http = True
請問這個是要手動加入setting.ini裡面嗎?

**Comment by eight04** [comment]
我沒辦法重現這個 bug，tumblr 會把 HTTPS 導向 HTTP︰
![image](https://user-images.githubusercontent.com/1324510/33781338-287b4062-dc8f-11e7-8a28-052af8b93d3d.png)
你下載的網址是？

**Comment by eight04** [comment]
2017.12.9 後新增兩個設定︰

* `full_size` - 下載原圖
* `insecure_http` - 使用 HTTP 下載

如果下載原圖時還會遇到這個錯誤就把 `insecure_http` 也打開吧。
