### ISSUE TITLE
漫畫櫃解析出錯

### ISSUE THREAD

**Issue by IthildinX** [eight04/ComicCrawler#93]
更新2018.1.30後發生
*程式中分類為看漫畫 但網站現在好像改叫漫畫櫃

網址
http://tw.manhuagui.com/comic/26767/

錯誤訊息
https://i.imgur.com/ejNEBFH.png

CMD紀錄
Start analyzing http://tw.manhuagui.com/comic/26767/
Traceback (most recent call last):
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\core\__init__.py", line 597, in analyze
    Analyzer(mission).analyze()
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\core\__init__.py", line 708, in analyze
    self.do_analyze()
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\core\__init__.py", line 731, in do_analyze
    self.html = self.downloader.html(self.mission.url, raise_429=False)
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\core\__init__.py", line 248, in html
    **kwargs
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\core\grabber.py", line 120, in grabhtml
    r = grabber(*args, **kwargs)
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\core\grabber.py", line 80, in grabber
    r = await_(do_request, s, url, params, proxies, method, data, raise_429)
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\worker\__init__.py", line 645, in wrapped
    return f(*args, **kwargs)
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\worker\__init__.py", line 657, in await_
    return async_(callback, *args, **kwargs).get()
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\worker\__init__.py", line 511, in get
    raise err
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\worker\__init__.py", line 384, in wrap_worker
    self.ret = self.worker(*args, **kwargs)
  File "c:\users\ithildin\appdata\local\programs\python\python36\lib\site-packages\comiccrawler\core\grabber.py", line 94, in do_request
    content_length = int(r.headers.get("Content-Length"))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by eight04** [comment]
Fixed in 2018.1.30.1.
